/* 2FLY live Music V2: physical CD archive on the existing global shell. */
(() => {
  'use strict';
  const archive = [
    {title:'Aye I Wish You The Merriest Christmas',year:'ARCHIVE',cover:'assets/music-archive/aye-i-wish-you-the-merriest-christmas.jpg',desc:'An earlier 2FLY holiday project returning as part of the official physical-media archive.'},
    {title:'BBL',year:'ARCHIVE',cover:'assets/music-archive/bbl.jpg',desc:'An early 2FLY project preserved in its original visual identity and returned to the official catalog.'},
    {title:'Better Late Than Never',year:'2007',cover:'assets/music-archive/better-late-than-never.jpg',desc:'An older project returning to the catalog with the original artwork kept at the center of the presentation.'},
    {title:'The Youngstown Pride',year:'ARCHIVE',cover:'assets/music-archive/the-youngstown-pride.jpg',desc:'A hometown-centered release from the earlier catalog, preserved as part of the 2FLY discography.'},
    {title:'Flyzone',year:'ARCHIVE',cover:'assets/music-archive/flyzone.jpg',desc:'A bold older project restored to the binder as a selectable artwork insert and matching printed compact disc.'},
    {title:'Ghetto Gumbo',year:'ARCHIVE',cover:'assets/music-archive/ghetto-gumbo.jpg',desc:'A classic We Famous Entertainment-era project presented without redesigning the original cover artwork.'},
    {title:'My City Crazy',year:'ARCHIVE',cover:'assets/music-archive/my-city-crazy.jpg',desc:'A city-focused archive release displayed as physical media inside the interactive 2FLY binder.'},
    {title:'Ohydro',year:'ARCHIVE',cover:'assets/music-archive/ohydro.jpg',desc:'An older catalog project brought forward as part of the complete 2FLY physical-media archive.'},
    {title:'Please Believe It!',year:'ARCHIVE',cover:'assets/music-archive/please-believe-it.jpg',desc:'A legacy release returning to the catalog with its original visual identity intact.'}
  ];
  const q = s => document.querySelector(s);
  const qa = s => [...document.querySelectorAll(s)];
  const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const asset = p => typeof resolveAssetUrl === 'function' ? resolveAssetUrl(p) : p;
  let index = 0, page = 0;
  const perPage = 4;

  const css = `
  #view-music .page-hero,#view-music .music-catalog>.section-head{display:none!important}
  #view-music{background:#090806!important}
  .music-v2-live{--led:#149cff;--led2:#58caff;--gold:#d6a22d;min-height:calc(100vh - 72px);background:linear-gradient(180deg,#0c0907,#1a0e09 60%,#261307);color:#f5f0e8;padding:14px 12px 26px}
  .m2-layout{max-width:1760px;margin:auto;display:grid;grid-template-columns:180px minmax(680px,1fr) 330px;gap:14px;align-items:start}
  .m2-copy{padding:20px 0 0 8px}.m2-copy h1{font:1000 clamp(46px,4.5vw,74px)/.82 Arial;margin:0;letter-spacing:-.06em}.m2-copy p{font:900 18px/1.15 Arial;letter-spacing:.04em}.m2-copy em{display:block;margin-top:24px;color:#f0c442;font:700 29px/1 "Comic Sans MS",cursive;transform:rotate(-4deg)}
  .m2-center{min-width:0}.m2-stereo{height:390px;display:grid;grid-template-columns:200px minmax(390px,520px) 200px;gap:7px;align-items:end;justify-content:center}
  .m2-speaker{height:358px;background:linear-gradient(160deg,#211915,#070808 24%,#0b0b0b 75%,#17120f);border:1px solid #4b3a31;box-shadow:0 20px 32px #0008,inset 0 0 0 2px #ffffff08;display:flex;flex-direction:column;align-items:center;justify-content:space-around;padding:15px 12px}.m2-speaker:first-child{transform:translateX(-26px)}.m2-speaker:last-child{transform:translateX(26px)}
  .m2-driver{display:block;border-radius:50%;position:relative;background:radial-gradient(circle at 46% 43%,#232323 0 12%,#080808 13% 40%,#2b2723 41% 48%,#050505 49% 69%,#191715 70%);border:2px solid #292929;box-shadow:0 0 0 3px #090909,0 0 0 5px #149cffcc,0 0 18px #149cffaa,inset 0 0 16px #000}.m2-driver:after{content:"";position:absolute;inset:-5px;border-radius:50%;border:1px solid var(--led2);box-shadow:0 0 8px var(--led),0 0 20px #149cff66}.m2-t{width:52px;height:52px}.m2-m{width:92px;height:92px}.m2-s{width:162px;height:162px}
  .m2-deck{height:326px;background:linear-gradient(100deg,#74645b,#a39388 12%,#594b45 15%,#8e7b70 40%,#64544d 72%,#9c8b7f 88%,#62534c);border:1px solid #574841;box-shadow:0 24px 42px #0009,inset 0 0 0 2px #ffffff10;padding:18px 22px 12px;border-radius:3px}.m2-lid{height:42px;margin:-43px 26px 12px;background:linear-gradient(#39302c,#151312);border:1px solid #53463e;border-radius:8px 8px 2px 2px}.m2-screen{height:122px;background:linear-gradient(#090d11,#020406);border:3px solid #3b312d;color:var(--led2);padding:13px 20px;font:800 11px monospace;box-shadow:inset 0 0 15px #000,0 0 0 1px #8b7b70}.m2-screen-top{display:flex;justify-content:space-between}.m2-bars{display:flex;align-items:end;gap:4px;height:45px;margin-top:8px}.m2-bars i{width:10px;background:linear-gradient(#4bd8ff,#0785ee);box-shadow:0 0 7px #149cff77}.m2-bars i:nth-child(1){height:13px}.m2-bars i:nth-child(2){height:23px}.m2-bars i:nth-child(3){height:36px}.m2-bars i:nth-child(4){height:28px}.m2-bars i:nth-child(5){height:40px}.m2-bars i:nth-child(6){height:31px}.m2-bars i:nth-child(7){height:21px}.m2-bars i:nth-child(8){height:12px}.m2-time{text-align:right;font-size:22px;font-weight:900}.m2-knob{width:78px;height:78px;border-radius:50%;margin:10px auto;background:radial-gradient(circle at 35% 32%,#ddd4ce,#8c786b 25%,#b99169 35%,#54453e 45%,#302a28 53%,#b0a39a 70%,#5f514a 80%);border:4px solid #332c29;box-shadow:0 0 0 3px #149cff88,0 0 16px #149cff55}.m2-slot{height:21px;border-radius:10px;background:linear-gradient(#2a2421,#090909);border:1px solid #52463e}.m2-deck small{display:block;text-align:center;color:#201a18;font-weight:1000;font-size:8px;letter-spacing:.19em;margin-top:8px}
  .m2-props{height:4px;position:relative;z-index:4;pointer-events:none}.m2-spindle{position:absolute;left:20px;top:-30px;width:110px;height:76px}.m2-spindle b{position:absolute;left:4px;right:4px;bottom:0;height:48px;border-radius:50%/18%;background:repeating-linear-gradient(180deg,#ffffff77 0 1px,#0006 1px 4px),linear-gradient(90deg,#9c762a,#e6d6a3,#6ebeff,#d09557,#c6ced1);box-shadow:0 9px 14px #0008}.m2-spindle i{position:absolute;left:49px;bottom:38px;width:11px;height:37px;border-radius:6px 6px 0 0;background:#111;border:1px solid #555}.m2-jewels{position:absolute;right:22px;top:-38px;width:122px;height:80px}.m2-jewels i{position:absolute;width:112px;height:69px;right:0;background:linear-gradient(135deg,#ffffff30,#ffffff09);border:1px solid #ffffff33;box-shadow:0 8px 12px #0006,inset 0 0 0 2px #ffffff12}.m2-jewels i:nth-child(2){top:9px;right:8px}.m2-jewels i:nth-child(3){top:18px;right:16px}.m2-jewels i:nth-child(4){top:27px;right:24px}
  .m2-binder-zone{display:grid;grid-template-columns:42px minmax(0,1fr) 42px;gap:8px;align-items:center;margin-top:10px}.m2-arrow{width:42px;height:42px;border-radius:50%;border:1px solid #9b825e;background:#050505cc;color:#fff;font-size:28px}.m2-arrow:disabled{opacity:.22}.m2-binder{background:linear-gradient(#171310,#090807 70%,#0d0b09);border:1px solid #5d4733;border-radius:16px;padding:15px 17px 16px;box-shadow:0 16px 34px #0009,inset 0 0 0 2px #ffffff09}.m2-binder-head{display:flex;justify-content:space-between;color:#a89680;font-size:7px;letter-spacing:.17em;font-weight:900;padding-bottom:10px}.m2-binder-head strong{color:#e0bb65}.m2-grid{display:grid;grid-template-columns:repeat(4,minmax(110px,1fr));gap:11px}.m2-pair{display:grid;grid-template-rows:150px 150px;gap:8px}.m2-pocket{position:relative;border:1px solid #e6d8c444;background:linear-gradient(135deg,#ffffff16,#ffffff05);overflow:hidden;padding:7px;color:#e5ddd0;cursor:pointer;transition:.15s}.m2-pocket:hover{transform:translateY(-2px);border-color:#a48b62}.m2-pair.selected .m2-pocket{border-color:var(--led);box-shadow:inset 0 0 0 1px var(--led),0 0 11px #149cff55}.m2-cover img{width:100%;height:100%;object-fit:contain;background:#0b0b0b}.m2-pocket small{position:absolute;z-index:3;left:7px;right:7px;bottom:7px;background:#000b;padding:4px;text-align:center;font-size:6px;letter-spacing:.1em;font-weight:900}.m2-discface{width:min(118px,78%);aspect-ratio:1;border-radius:50%;position:absolute;left:50%;top:47%;transform:translate(-50%,-50%);overflow:hidden;background:conic-gradient(#ddd,#777,#f2f2ed,#999,#ddd,#888);box-shadow:0 0 0 3px #c6c6c2,0 0 0 5px #5e5e5b,0 8px 15px #0007}.m2-discface img{width:100%;height:100%;object-fit:cover}.m2-discface:after{content:"";position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);width:29%;height:29%;border-radius:50%;background:#111;border:7px solid #dcdcd8cc;box-shadow:0 0 0 1px #777}
  .m2-hud{background:linear-gradient(#070808,#040404);border:1px solid #8b6919;padding:16px;min-height:650px;box-shadow:0 16px 30px #0007}.m2-hud>small{display:block;color:#efb52f;font-size:8px;letter-spacing:.2em;font-weight:1000;margin-bottom:10px}.m2-hud-cover{aspect-ratio:1;border:1px solid #806d42;padding:5px;background:#111}.m2-hud-cover img{width:100%;height:100%;object-fit:contain;background:#0b0b0b}.m2-hud h2{font:800 clamp(26px,2.4vw,40px)/.94 Georgia;margin:14px 0 10px}.m2-meta{color:#cfc7bc;font-size:9px;letter-spacing:.12em;font-weight:800}.m2-hud p{font:14px/1.47 Georgia;color:#ddd5ca}.m2-status{border:2px solid #bb8b1c;color:#ffc72e;text-align:center;font-weight:1000;font-size:14px;line-height:1.15;letter-spacing:.04em;padding:12px 8px;margin:13px 0}.m2-list-title{font-size:7px;letter-spacing:.18em;color:#d8a738;font-weight:1000;border-top:1px solid #40351f;padding-top:13px}.m2-list{list-style:none;padding:0;margin:9px 0 13px;display:grid;gap:4px}.m2-list li{display:grid;grid-template-columns:27px 1fr;gap:7px;background:#11100e;border:1px solid #24211d;padding:7px}.m2-list b{color:#d8a738;font-size:7px}.m2-list span{font-size:9px}.m2-pending{width:100%;padding:11px;border:0;background:#372d18;color:#bea864;font-size:8px;font-weight:1000;letter-spacing:.12em}.m2-note{color:#777168!important;font:7px/1.45 Arial!important}
  @media(max-width:1280px){.m2-layout{grid-template-columns:150px minmax(600px,1fr) 290px}.m2-stereo{grid-template-columns:165px minmax(350px,470px) 165px}.m2-s{width:140px;height:140px}.m2-pair{grid-template-rows:125px 125px}}
  @media(max-width:980px){.m2-layout{grid-template-columns:1fr}.m2-copy{display:none}.m2-hud{margin-top:12px;min-height:0}.m2-stereo{grid-template-columns:150px minmax(320px,430px) 150px}.m2-grid{grid-template-columns:repeat(2,minmax(130px,1fr))}.m2-pair{grid-template-rows:160px 160px}}
  @media(max-width:680px){.music-v2-live{padding:8px}.m2-stereo{height:300px;grid-template-columns:88px minmax(220px,1fr) 88px}.m2-speaker{height:270px;padding:10px 5px}.m2-t{width:34px;height:34px}.m2-m{width:58px;height:58px}.m2-s{width:82px;height:82px}.m2-deck{height:250px;padding:12px}.m2-lid{display:none}.m2-screen{height:90px;padding:9px}.m2-bars{height:30px}.m2-knob{width:58px;height:58px}.m2-pair{grid-template-rows:125px 125px}.m2-binder-zone{grid-template-columns:34px 1fr 34px}.m2-arrow{width:34px;height:34px}}
  `;

  function ensureStyle(){ if(!q('#musicV2LiveStyle')){const s=document.createElement('style');s.id='musicV2LiveStyle';s.textContent=css;document.head.appendChild(s);} }
  function drawHud(){
    const a=archive[index], hud=q('#m2Hud'); if(!hud||!a)return;
    const cover=asset(a.cover);
    const discNo=q('#m2DiscNo'); if(discNo)discNo.textContent=String(index+1).padStart(2,'0');
    hud.innerHTML=`<small>SELECTED DISC</small><div class="m2-hud-cover"><img src="${cover}" alt="${esc(a.title)} artwork"></div><h2>${esc(a.title)}</h2><div class="m2-meta">${esc(a.year)} · 2FLY KEITH LOGAN</div><p>${esc(a.desc)}</p><div class="m2-status">RE-RELEASE DATE COMING SOON</div><div class="m2-list-title">CATALOG / DISCOGRAPHY</div><ol class="m2-list"><li><b>01</b><span>${esc(a.title)}</span></li><li><b>02</b><span>ARCHIVE PROJECT</span></li><li><b>03</b><span>AUDIO TO BE ADDED</span></li></ol><button class="m2-pending" disabled>AUDIO COMING SOON</button><p class="m2-note">Original artwork is preserved. Audio and final track data will be attached to these archive entries later.</p>`;
  }
  function drawPage(){
    const grid=q('#m2Grid'); if(!grid)return;
    const pages=Math.ceil(archive.length/perPage), start=page*perPage;
    q('#m2Page').textContent=`PAGE ${String(page+1).padStart(2,'0')} / ${String(pages).padStart(2,'0')}`;
    grid.innerHTML=archive.slice(start,start+perPage).map((a,local)=>{const i=start+local,cover=asset(a.cover);return `<article class="m2-pair ${i===index?'selected':''}" data-pair="${i}"><button class="m2-pocket m2-cover" data-album="${i}" type="button"><img src="${cover}" alt="${esc(a.title)} original artwork"><small>ARTWORK INSERT</small></button><button class="m2-pocket" data-album="${i}" type="button"><span class="m2-discface"><img src="${cover}" alt=""></span><small>MATCHING COMPACT DISC</small></button></article>`}).join('');
    qa('#m2Grid [data-album]').forEach(b=>b.onclick=()=>{index=+b.dataset.album;qa('.m2-pair').forEach(p=>p.classList.toggle('selected',+p.dataset.pair===index));drawHud();});
    q('#m2Prev').disabled=page===0;q('#m2Next').disabled=page===pages-1;
  }
  function render(){
    if((location.hash||'#home').slice(1).split('?')[0]!=='music')return;
    const view=q('#view-music'); if(!view)return; ensureStyle();
    view.innerHTML=`<section class="music-v2-live"><div class="m2-layout"><aside class="m2-copy"><h1>MUSIC</h1><p>COLLECT.<br>EXPLORE.<br>PRESS PLAY.</p><em>Music Lives Here.</em></aside><div class="m2-center"><div class="m2-stereo"><div class="m2-speaker"><i class="m2-driver m2-t"></i><i class="m2-driver m2-m"></i><i class="m2-driver m2-s"></i></div><div class="m2-deck"><div class="m2-lid"></div><div class="m2-screen"><div class="m2-screen-top"><span>DISC <b id="m2DiscNo">01</b></span><span>TRACK 01</span></div><div class="m2-bars"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><div class="m2-time">00:00</div></div><div class="m2-knob"></div><div class="m2-slot"></div><small>2FLY · MUSIC LIVES HERE</small></div><div class="m2-speaker"><i class="m2-driver m2-t"></i><i class="m2-driver m2-m"></i><i class="m2-driver m2-s"></i></div></div><div class="m2-props"><div class="m2-spindle"><b></b><i></i></div><div class="m2-jewels"><i></i><i></i><i></i><i></i></div></div><div class="m2-binder-zone"><button id="m2Prev" class="m2-arrow" type="button" aria-label="Previous binder page">‹</button><div class="m2-binder"><div class="m2-binder-head"><span>2FLY DISC ARCHIVE</span><strong id="m2Page"></strong><span>SELECT COVER OR DISC</span></div><div id="m2Grid" class="m2-grid"></div></div><button id="m2Next" class="m2-arrow" type="button" aria-label="Next binder page">›</button></div></div><aside id="m2Hud" class="m2-hud"></aside></div></section>`;
    const pages=Math.ceil(archive.length/perPage);
    q('#m2Prev').onclick=()=>{if(page>0){page--;index=page*perPage;drawPage();drawHud();}};
    q('#m2Next').onclick=()=>{if(page<pages-1){page++;index=page*perPage;drawPage();drawHud();}};
    drawPage();drawHud();
  }
  window.addEventListener('hashchange',()=>setTimeout(render,0));
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(render,0));else setTimeout(render,0);
})();
