import assert from 'node:assert/strict';
import {NavigationSafety,NAV,SAFE_ARRIVALS,validateArrival} from '../app-v23/state/navigation-safety.js';
import {GALAXY_THEMES} from '../app-v23/types.js';
import fs from 'node:fs';
const boundaries=Object.values(GALAXY_THEMES).map(g=>{const r=(g.status==='showcase'?12450:g.status==='uncharted'?7600:9000)*(g.scale||1);return {id:g.id,center:{x:g.worldOffset[0],y:g.worldOffset[1],z:g.worldOffset[2]},entryRadius:r*1.06,exitRadius:r*1.80}});
let now=0,returns=[],events=[];const make=()=>new NavigationSafety({boundaries,now:()=>now,random:()=>.42,onReturn:p=>returns.push(p),onChange:s=>events.push(s)});
const point=(r)=>({x:0,y:0,z:r});const step=(n,p,seconds,extra={})=>{for(let t=0;t<seconds;t+=.05){now+=50;n.update(.05,{position:p,...extra});}};
const tests=[];const test=(name,fn)=>{fn();tests.push({name,passed:true})};
test('entry is exclusive and stable across entry-threshold jitter',()=>{const n=make(),g=boundaries.find(g=>g.id==='G2025');step(n,point(g.entryRadius-1),.05);assert.equal(n.state,NAV.ENTERING);assert.equal(n.galaxyId,'G2025');assert.equal(n.canSelectGalaxy,false);step(n,point(g.entryRadius+80),2);assert.equal(n.state,NAV.INSIDE);for(let i=0;i<60;i++)step(n,point(g.entryRadius+(i%2?200:-200)),.05);assert.equal(n.entryCount,1);assert.equal(n.exitCount,0);step(n,point(g.exitRadius+1),.05);assert.equal(n.state,NAV.EXITING);assert.equal(n.galaxyId,null);assert.equal(n.canSelectGalaxy,false);step(n,point(g.exitRadius+1),1.5);assert.equal(n.state,NAV.UNIVERSE);assert.equal(n.selection,null);});
test('every configured galaxy has its own exclusive boundary',()=>{for(const g of boundaries){const n=make();step(n,g.center,1.7);assert.equal(n.galaxyId,g.id);assert.equal(n.canSelectGalaxy,false);assert.equal(n.canSelectLocal(g.id),true);assert.equal(n.canTravelToGalaxy(boundaries.find(x=>x.id!==g.id).id),false);}});
test('two-stage confirmation blocks double clicks and one-event activation',()=>{const n=make();step(n,point(12000),1.6);let item={key:'audio',galaxyId:'G2025',world:()=>point(10000),range:8000};assert.equal(n.choose(item,{detail:1},point(12000)),'selected');assert.equal(n.state,NAV.SELECTED);assert.equal(n.content,false);now+=90;assert.equal(n.choose(item,{detail:2},point(12000)),'wait');now+=600;assert.equal(n.choose(item,{detail:3},point(12000)),'wait');now+=600;assert.equal(n.choose(item,{detail:1},point(12000)),'activate');assert.equal(n.state,NAV.CONTENT);assert.equal(n.selection,null);n.closeContent();assert.equal(n.state,NAV.INSIDE);});
test('different selection, clear, range exit, and wrong-galaxy gates',()=>{const n=make();step(n,point(12000),1.6);const a={key:'a',galaxyId:'G2025',world:()=>point(12000),range:2000};assert.equal(n.choose({...a,galaxyId:'G2000'},{},point(12000)),'blocked');n.choose(a,{},point(12000));now+=600;assert.equal(n.choose({...a,key:'b'},{},point(12000)),'selected');assert.equal(n.content,false);n.clearSelection();assert.equal(n.state,NAV.INSIDE);n.choose(a,{},point(12000));step(n,point(15000),.1);assert.equal(n.selection,null);});
function thrust(n,seconds,start=95000,extra={}){for(let t=0;t<seconds;t+=.05){now+=50;n.update(.05,{position:point(start+t*15000),velocity:point(15000),thrust:true,...extra})}}
test('short, stationary and inward thrust never charges',()=>{for(const mode of ['short','stationary','inward']){const n=make();if(mode==='short')thrust(n,2);if(mode==='stationary')step(n,point(100000),10,{thrust:true,velocity:point(15000)});if(mode==='inward')thrust(n,7,100000,{velocity:point(-15000)});assert.notEqual(n.state,NAV.CHARGING);assert.equal(n.warpCount,0);}});
test('release/menu/reversal cancel charge',()=>{for(const override of [{thrust:false},{menu:true},{velocity:point(-15000)}]){const n=make();thrust(n,3.4);assert.equal(n.state,NAV.CHARGING);n.update(.05,{position:point(146000),velocity:point(15000),thrust:true,...override});assert.equal(n.state,NAV.UNIVERSE);assert.equal(n.charge,0);}});
test('sustained outward travel reaches transit and a validated, varying safe arrival',()=>{const n=make();thrust(n,6.3);assert.equal(n.state,NAV.TRANSIT);assert.equal(n.locked,true);assert.equal(n.galaxyId,null);step(n,point(190000),2.5);assert.equal(n.state,NAV.ARRIVAL);assert.ok(validateArrival(returns.at(-1),boundaries));assert.equal(n.charge,0);step(n,returns.at(-1),1.5);assert.equal(n.state,NAV.UNIVERSE);const first=returns.at(-1);step(n,first,3);thrust(n,6.4);step(n,point(190000),2.5);assert.ok(validateArrival(returns.at(-1),boundaries));assert.notDeepEqual(returns.at(-1),first);});
test('all configured spawn candidates clear all galaxy/geometry envelopes',()=>{assert.ok(SAFE_ARRIVALS.every(p=>validateArrival(p,boundaries)));assert.equal(validateArrival(point(0),boundaries),false);assert.equal(validateArrival(SAFE_ARRIVALS[0],boundaries,[{center:SAFE_ARRIVALS[0],radius:500}]),false);});
console.log(JSON.stringify({passed:tests.length,tests},null,2));

