const test=require('node:test'),assert=require('node:assert/strict');
const D=require('../js/player-downloads');
const audio=Uint8Array.from([73,68,51,...Array(100).fill(32)]);
test('catalog preserves album identity and excludes upcoming releases',()=>{const c=D.catalog([{id:'a',title:'Album',tracks:[{title:'Song',audio:'a.mp3'},{title:'Missing'}]},{id:'b',upcoming:true,audio:'b.mp3'}],'https://example.com/base/');assert.equal(c.length,1);assert.equal(c[0].url,'https://example.com/base/a.mp3');assert.equal(c[0].isAlbum,true);});
test('corrupt storage is safe and duplicates are removed',()=>{assert.deepEqual(D.readFavorites('{'),[]);assert.deepEqual(D.readFavorites('["a","a",7]'),['a']);});
test('download rejects HTML, HTTP errors, empty and truncated responses',async()=>{for(const response of [new Response('<html>Error</html>'),new Response('',{status:404}),new Response(''),new Response(audio,{headers:{'content-length':'900'}})])await assert.rejects(D.fetchAudio('https://example.com/a',{fetcher:async()=>response}));});
test('valid audio survives byte for byte',async()=>{assert.deepEqual(await D.fetchAudio('https://example.com/a',{fetcher:async()=>new Response(audio)}),audio);});
test('cancellation and timeout abort fetching',async()=>{const fetcher=(_,o)=>new Promise((resolve,reject)=>{if(o.signal.aborted)reject(new Error('aborted'));o.signal.addEventListener('abort',()=>reject(new Error('aborted')));});const c=new AbortController();c.abort();await assert.rejects(D.fetchAudio('x',{fetcher,signal:c.signal}),/aborted/);await assert.rejects(D.fetchAudio('x',{fetcher,timeout:5}),/aborted/);});
test('ZIP CRC matches standard reference and paths are safe',async()=>{assert.equal(D.crc32(new TextEncoder().encode('123456789')),0xcbf43926);assert.throws(()=>D.zip([{name:'../x',bytes:audio}]));assert.throws(()=>D.zip([{name:'x',bytes:audio},{name:'x',bytes:audio}]));const zip=D.zip([{name:'Album/01 - Café.mp3',bytes:audio}]);const b=new DataView(await zip.arrayBuffer());assert.equal(b.getUint32(0,true),0x04034b50);assert.equal(b.getUint32(b.byteLength-22,true),0x06054b50);assert.equal(b.getUint16(6,true),0x800);});
