// Run against a static server for this checkout; requires Playwright and Edge.
const fs=require('fs'),path=require('path');
const out=fs.mkdtempSync(path.join(require('os').tmpdir(),'2fly-player-qa-'));
const base=process.env.PLAYER_QA_URL||'http://127.0.0.1:8765';
const {chromium}=require('playwright');const assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});const context=await browser.newContext({acceptDownloads:true,viewport:{width:1366,height:900}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/pages/music-catalog.html');await page.waitForFunction(()=>app.projects.length>0);const select=async(id,index=0)=>{await page.evaluate(({id,index})=>{const p=app.projects.find(x=>x.id===id),t=p.tracks?.[index];loadProjectAudio({...p,title:t?.title||p.title,audio:t?.audio||p.audio,albumId:p.tracks?p.id:null,albumTrackIndex:index},false);},{id,index});await page.waitForTimeout(100);};const saveFile=async(name)=>{await page.locator('[data-ready]').waitFor({state:'visible',timeout:180000});console.log(name,await page.locator('.player-notice p').textContent());const waiting=page.waitForEvent('download');await page.locator('[data-ready]').click();const download=await waiting;await download.saveAs(path.join(out,name));assert.equal(await download.failure(),null);await page.locator('[data-dismiss]').click();};
await select('artificial-love',2);await page.locator('.player-heart').click();await page.locator('[data-dismiss]').click();await page.locator('.player-download-actions [data-download=album]').click();await saveFile('album.zip');
await select('fire');await page.locator('.player-heart').click();await page.locator('[data-dismiss]').click();await page.locator('.player-download-actions [data-download=song]').click();await saveFile('hosted-song.mp3');await page.locator('.player-download-actions [data-download=hearted]').click();await saveFile('all-hearted.zip');
await page.locator('.player-library-toggle').click();await page.locator('[data-play-all]').click();await page.waitForFunction(()=>!document.querySelector('#globalAudio').paused&&document.querySelector('#globalAudio').currentTime>0);console.log('QUEUE PLAYING',await page.locator('#playerTitle').textContent());await page.locator('#playerNext').click();await page.waitForFunction(()=>document.querySelector('#playerTitle').textContent==='Thru the Fire');console.log('QUEUE NEXT');await page.locator('.player-library li').last().locator('button').last().click();assert.equal(await page.locator('#playerTitle').textContent(),'Thru the Fire');await page.locator('[data-close]').click();
await select('artificial-love',0);await page.route('**/01-beautiful-mind.mp3',route=>route.fulfill({status:200,contentType:'text/html',body:'<html>broken file</html>'}));await page.locator('.player-download-actions [data-download=song]').click();await page.locator('[data-retry]').waitFor({state:'visible'});assert.equal(await page.locator('[data-ready]').isVisible(),false);console.log('ERROR HANDLED',await page.locator('.player-notice p').textContent());await page.unroute('**/01-beautiful-mind.mp3');await page.locator('[data-retry]').click();await saveFile('retried-song.mp3');
await page.route('**/01-beautiful-mind.mp3',async route=>{await new Promise(r=>setTimeout(r,3000));await route.abort().catch(()=>{});});await page.locator('.player-download-actions [data-download=song]').click();await page.locator('[data-cancel]').click();await page.waitForFunction(()=>document.querySelector('.player-notice p').textContent.includes('canceled'));console.log('CANCEL HANDLED');await page.unroute('**/01-beautiful-mind.mp3');await page.locator('[data-dismiss]').click();
for(const route of ['home','featured','playables','videos','music']){await page.evaluate(route=>location.hash=route,route);await page.waitForTimeout(800);assert.equal(await page.locator('.player-heart').count(),1);console.log('ROUTE',route);}
await page.setViewportSize({width:360,height:800});await page.locator('.player-download-toggle').click();assert.equal(await page.locator('.player-download-actions [data-download=song]').isVisible(),true);assert.equal(await page.locator('.global-player').evaluate(e=>e.scrollWidth<=e.clientWidth),true);await page.screenshot({path:path.join(out,'player-mobile-downloads.png')});console.log('MOBILE DOWNLOADS');assert.deepEqual(errors,[]);console.log('NO JS ERRORS');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
