(()=>{
'use strict';
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d',{alpha:false});
const W=canvas.width,H=canvas.height, fatal=document.getElementById('fatal');
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), lerp=(a,b,t)=>a+(b-a)*t, ease=t=>t*t*(3-2*t), rand=(a,b)=>a+Math.random()*(b-a);
window.addEventListener('error',e=>{fatal.style.display='block';fatal.textContent='GAME ERROR: '+e.message});
window.addEventListener('unhandledrejection',e=>{fatal.style.display='block';fatal.textContent='ASYNC ERROR: '+String(e.reason||'unknown')});
const SONG='https://static.wixstatic.com/mp3/85e419_62dfb4b5acfc4747a02ad9eaeb643f29.mp3',A='assets/production/',B='assets/backgrounds/';
const M={
 sky:B+'scene1_sky.jpg',runway:B+'runway_final.jpg',maze:B+'maze_final.jpg',bossBg:B+'boss_final.jpg',clouds:B+'cloud_layer.png',rain:B+'rain.png',
 plane:[A+'plane_idle.png',A+'plane_bank.png',A+'plane_burn.png',A+'plane_explode.png'],boss:A+'algorithm_boss.png',explosion:A+'explosion.png',
 aerialDive:[0,1,2,3].map(i=>A+`aerial_dive_${i}.png`),aerialResist:[0,1,2,3].map(i=>A+`aerial_resist_${i}.png`),aerialSpin:[0,1,2,3].map(i=>A+`aerial_spin_${i}.png`),
 runBack:[0,1,2,3].map(i=>A+`run_back_${i}.png`),runFront:[0,1,2].map(i=>A+`run_front_${i}.png`),runJump:[0,1,2].map(i=>A+`run_jump_${i}.png`),
 aimIdle:[0,1,2,3,4,5].map(i=>A+`aim_up_idle_${i}.png`),aimFire:[0,1,2,3,4,5].map(i=>A+`aim_up_fire_${i}.png`),aimJump:[0,1,2,3,4].map(i=>A+`aim_up_jump_${i}.png`),
 pianoIdle:[0,1,2].map(i=>A+`piano_idle_${i}.png`),pianoDrive:[0,1,2].map(i=>A+`piano_drive_${i}.png`),pianoBoost:[0,1,2].map(i=>A+`piano_boost_${i}.png`),pianoLeft:[0,1,2].map(i=>A+`piano_left_${i}.png`),pianoRight:[0,1,2].map(i=>A+`piano_right_${i}.png`),pianoFire:[0,1,2,3].map(i=>A+`piano_fire_${i}.png`),
 ramps:[0,1,2,3].map(i=>A+`route_ramp_${i}.png`),routeEnemies:[0,1,2,3,4].map(i=>A+`route_enemy_${i}.png`),platforms:[0,1,2,3,4,5,6].map(i=>A+`platform_${i}.png`),
 bots:['bot_surveillance_orb','bot_tracking_orb','bot_interceptor','bot_censorship_bot','bot_firewall_sentinel','bot_data_miner','bot_corrupted_jammer','bot_heavy_assault','bot_manipulator','bot_shield_projector'].map(x=>A+x+'.png')
};
const imgs={};
function loadImage(src){return new Promise((res,rej)=>{const im=new Image();im.onload=()=>res(im);im.onerror=()=>rej(new Error(src));im.src=src})}
async function loadAll(){let pairs=[];for(const [k,v] of Object.entries(M)){if(typeof v==='string')pairs.push([k,v]);else v.forEach((s,i)=>pairs.push([`${k}_${i}`,s]))}const rr=await Promise.allSettled(pairs.map(async p=>[p[0],await loadImage(p[1])]));let miss=0;rr.forEach(r=>{if(r.status==='fulfilled')imgs[r.value[0]]=r.value[1];else miss++});return miss}
const keys={};let debug=false;addEventListener('keydown',e=>{keys[e.code]=true;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();if(e.code==='F2')debug=!debug;tryAudio()});addEventListener('keyup',e=>keys[e.code]=false);canvas.addEventListener('pointerdown',tryAudio);
let audio=null,audioStatus='READY',audioPass=0,songDur=128,totalDur=256;
const BASE=[0,17,60,67,118,128,183,191,249,256]; // intro,dive,t1,runway,t2,maze,t3,boss,finale,end
let cues=BASE.slice();
function scaleCues(){const f=(songDur*2)/256;cues=BASE.map(x=>x*f);totalDur=songDur*2}
function tryAudio(){if(!started)return;if(!audio){audio=new Audio(SONG);audio.preload='auto';audio.volume=.84;audio.loop=false;audio.playbackRate=1;audio.addEventListener('loadedmetadata',()=>{if(Number.isFinite(audio.duration)&&audio.duration>30){songDur=audio.duration;scaleCues()}});audio.addEventListener('ended',()=>{if(audioPass===0){audioPass=1;audio.currentTime=0;audio.play().then(()=>audioStatus='PLAYING • PASS 2').catch(()=>audioStatus='CLICK TO RETRY')}else audioStatus='MUSIC COMPLETE'})}if(audio.paused&&audioPass<2)audio.play().then(()=>audioStatus=`PLAYING • PASS ${audioPass+1}`).catch(()=>audioStatus='CLICK / KEY TO RETRY')}
let started=false,last=0,clock=0,score=0,combo=0,hp=5,scene='intro',sceneLocal=0;
let hero={x:640,y:520,frame:0,ft:0,jump:0,jv:0,spinT:0},plane={x:650,y:270},vehicle={x:640,y:575,vx:0,air:0,av:0},boss={x:640,y:165,hp:120,max:120};
let enemies=[],shots=[],enemyShots=[],routeObjects=[],platforms=[],spawnT=.5,fireT=0,specialT=0,escapeTaps=0,cam={x:0,y:0,zoom:1,tx:0,ty:0,tz:1},floorBroken=false,finalCharge=0;
function reset(){clock=0;score=0;combo=0;hp=5;scene='intro';sceneLocal=0;hero={x:640,y:520,frame:0,ft:0,jump:0,jv:0,spinT:0};plane={x:650,y:270};vehicle={x:640,y:575,vx:0,air:0,av:0};boss={x:640,y:165,hp:120,max:120};enemies=[];shots=[];enemyShots=[];routeObjects=[];platforms=[];spawnT=.5;fireT=0;specialT=0;escapeTaps=0;cam={x:0,y:0,zoom:1,tx:0,ty:0,tz:1};floorBroken=false;finalCharge=0;audioPass=0;if(audio){audio.pause();try{audio.currentTime=0}catch(e){}}audioStatus='STARTING…'}
function start(){reset();started=true;document.getElementById('start-overlay').classList.add('hidden');tryAudio();last=performance.now();requestAnimationFrame(loop)}
function im(k,i=0){return imgs[`${k}_${i}`]||imgs[k]}
function drawCover(img,x=0,y=0,w=W,h=H,zoom=1,panX=0,panY=0,alpha=1){if(!img)return;ctx.save();ctx.globalAlpha=alpha;const rw=w*zoom,rh=h*zoom;ctx.drawImage(img,x-(rw-w)/2+panX,y-(rh-h)/2+panY,rw,rh);ctx.restore()}
function drawSprite(img,x,y,h,alpha=1,rot=0){if(!img)return;const w=img.width/img.height*h;ctx.save();ctx.globalAlpha=alpha;ctx.translate(x,y);ctx.rotate(rot);ctx.drawImage(img,-w/2,-h/2,w,h);ctx.restore();return {w,h}}
function anim(arr,rate=.1){hero.ft+=dtGlobal;if(hero.ft>rate){hero.ft=0;hero.frame++}return im(arr,hero.frame%(M[arr]?.length||1))}
function camera(dt){cam.x=lerp(cam.x,cam.tx,1-Math.pow(.001,dt));cam.y=lerp(cam.y,cam.ty,1-Math.pow(.001,dt));cam.zoom=lerp(cam.zoom,cam.tz,1-Math.pow(.002,dt))}
function inputX(){return (keys.ArrowRight||keys.KeyD?1:0)-(keys.ArrowLeft||keys.KeyA?1:0)}function inputY(){return (keys.ArrowDown||keys.KeyS?1:0)-(keys.ArrowUp||keys.KeyW?1:0)}
function sceneFor(t){if(t<cues[1])return'intro';if(t<cues[2])return'dive';if(t<cues[3])return't1';if(t<cues[4])return'runway';if(t<cues[5])return't2';if(t<cues[6])return'maze';if(t<cues[7])return't3';if(t<cues[8])return'boss';if(t<cues[9])return'finale';return'end'}
function local(a,b){return clamp((clock-cues[a])/(cues[b]-cues[a]),0,1)}
function setScene(s){if(scene===s)return;scene=s;sceneLocal=0;enemies=[];enemyShots=[];shots=[];routeObjects=[];spawnT=.3;if(s==='runway'){hero.x=640;hero.jump=0}if(s==='maze'){vehicle.x=640;vehicle.y=590;seedRoute()}if(s==='boss'){hero.x=640;hero.y=590;boss.hp=120;floorBroken=false;seedPlatforms()}}
function seedRoute(){routeObjects=[];for(let i=0;i<18;i++)routeObjects.push({z:i*260+450,type:i%5===2?'ramp':(i%4===0?'enemy':'gate'),lane:[-1,0,1][i%3],curve:Math.sin(i*.9)})}
function seedPlatforms(){platforms=[{x:230,y:610,w:290,i:0},{x:565,y:555,w:250,i:2},{x:880,y:620,w:300,i:1},{x:430,y:425,w:200,i:4},{x:780,y:390,w:220,i:5}]}
function spawnEnemy(kind='air'){if(enemies.length>=6)return;const i=Math.floor(Math.random()*M.bots.length);enemies.push({x:rand(100,1180),y:kind==='dive'?H+80:rand(120,300),vx:rand(-35,35),vy:kind==='dive'?-rand(95,155):rand(20,50),i,hp:i===7?5:2,cool:rand(3.5,5.4),label:['SURVEILLANCE','TRACKING','INTERRUPTION','CENSORSHIP','FIREWALL','DATA','JAMMER','AMPLIFICATION','MANIPULATION','SHIELD'][i]})}
function updateEnemies(dt,kind){spawnT-=dt;if(spawnT<=0){spawnEnemy(kind);spawnT=rand(.9,1.45)}const target=scene==='maze'?vehicle:hero;enemies.forEach(e=>{e.x+=e.vx*dt;e.y+=e.vy*dt;e.cool-=dt;if(e.cool<=0&&enemyShots.length<4){e.cool=rand(4,6);const dx=target.x-e.x,dy=target.y-e.y,l=Math.hypot(dx,dy)||1;enemyShots.push({x:e.x,y:e.y,vx:dx/l*170,vy:dy/l*170,life:4})}});enemies=enemies.filter(e=>e.hp>0&&e.x>-150&&e.x<W+150&&e.y>-180&&e.y<H+180);enemyShots.forEach(s=>{s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt});enemyShots=enemyShots.filter(s=>s.life>0)}
function fire(dir='up'){if(fireT>0)return;fireT=.20;const src=scene==='maze'?vehicle:hero;if(dir==='down')shots.push({x:src.x,y:src.y+25,vx:0,vy:650,life:1.6});else shots.push({x:src.x,y:src.y-45,vx:0,vy:-690,life:1.8})}
function updateCombat(dt,dir='up'){fireT=Math.max(0,fireT-dt);specialT=Math.max(0,specialT-dt);if(keys.Space)fire(dir);shots.forEach(s=>{s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt});for(const s of shots){for(const e of enemies)if(s.life>0&&e.hp>0&&Math.hypot(s.x-e.x,s.y-e.y)<58){s.life=0;e.hp--;score+=175;combo++;}if(scene==='boss'&&s.life>0&&Math.hypot(s.x-boss.x,s.y-boss.y)<120){s.life=0;boss.hp-=1.15;score+=40}}shots=shots.filter(s=>s.life>0&&s.y>-100&&s.y<H+100);if(keys.ShiftLeft&&specialT<=0){specialT=3.5;enemyShots=[];enemies.forEach(e=>e.hp-=1)}const t=scene==='maze'?vehicle:hero;for(const s of enemyShots)if(s.life>0&&Math.hypot(s.x-t.x,s.y-t.y)<34){s.life=0;hp=Math.max(1,hp-1);combo=0}}
function drawEnemies(){ctx.textAlign='center';enemies.forEach(e=>{drawSprite(im('bots',e.i),e.x,e.y,e.i===7?170:135);ctx.font='700 10px monospace';ctx.fillStyle='#78e6ff';ctx.fillText(e.label,e.x,e.y-82)});ctx.fillStyle='#ff5147';enemyShots.forEach(s=>{ctx.beginPath();ctx.arc(s.x,s.y,5,0,7);ctx.fill()});ctx.fillStyle='#72e9ff';shots.forEach(s=>{ctx.beginPath();ctx.arc(s.x,s.y,6,0,7);ctx.fill()})}
function intro(dt){const p=local(0,1);cam.tx=0;cam.ty=0;cam.tz=1+Math.sin(clock*.5)*.01;camera(dt);drawCover(im('sky'),0,0,W,H,cam.zoom);const pi=p<.35?0:p<.62?1:p<.84?2:3;plane.x=640+Math.sin(clock*1.4)*40;plane.y=260+Math.sin(clock*2)*10;drawSprite(im('plane',pi),plane.x,plane.y,pi===3?230:190);updateEnemies(dt,'air');drawEnemies();if((keys.ArrowUp||keys.KeyW)&&!keys._tap){escapeTaps++;keys._tap=true}else if(!(keys.ArrowUp||keys.KeyW))keys._tap=false;ctx.fillStyle='rgba(0,0,0,.62)';ctx.fillRect(450,630,380,40);ctx.fillStyle='#fff';ctx.font='900 17px Arial';ctx.textAlign='center';ctx.fillText(`TAP ↑ / W — ESCAPE  ${Math.min(100,escapeTaps*18)}%`,640,656)}
function dive(dt){const p=local(1,2),ix=inputX(),iy=inputY();const power=keys.ArrowDown||keys.KeyS,resist=keys.ArrowUp||keys.KeyW;cam.tx=ix*38;cam.ty=iy*24;cam.tz=power?.86:resist?1.06:1;camera(dt);drawCover(im('sky'),0,0,W,H,cam.zoom,cam.x,cam.y);hero.x=clamp(hero.x+ix*385*dt,120,1160);hero.y=clamp(hero.y+iy*300*dt,120,600);if(Math.abs(ix)>0&&Math.random()<dt*.8)hero.spinT=.34;hero.spinT=Math.max(0,hero.spinT-dt);let spr;if(hero.spinT>0)spr=anim('aerialSpin',.08);else if(resist)spr=anim('aerialResist',.11);else spr=anim('aerialDive',power?.075:.11);drawSprite(spr,hero.x,hero.y,resist?205:190);updateEnemies(dt,'dive');updateCombat(dt,'down');drawEnemies();ctx.fillStyle='#80e7ff';ctx.textAlign='center';ctx.font='800 13px Arial';ctx.fillText(power?'POWER DIVE':resist?'RESISTANCE':'FREEFALL',hero.x,hero.y+125)}
function transition1(dt){const p=local(2,3);cam.tz=lerp(.90,1.08,ease(p));camera(dt);drawCover(im('runway'),0,0,W,H,cam.zoom);hero.x=640;hero.y=lerp(150,545,ease(p));drawSprite(anim('aerialResist',.1),hero.x,hero.y,lerp(150,205,p));ctx.strokeStyle=`rgba(100,230,255,${1-p*.4})`;ctx.lineWidth=8;ctx.beginPath();ctx.ellipse(640,610,80+p*380,22+p*60,0,0,7);ctx.stroke();ctx.fillStyle='#fff';ctx.font='900 18px Arial';ctx.textAlign='center';ctx.fillText('HOLD ↑ / W — 808 BRACE',640,660)}
function runway(dt){const p=local(3,4),half=p<.52,ix=inputX();cam.tx=ix*32;cam.ty=0;cam.tz=half?lerp(1.06,.94,ease(p/.52)):lerp(.94,1.08,ease((p-.52)/.48));camera(dt);drawCover(im('runway'),0,0,W,H,cam.zoom,cam.x,0); // no vertical scrolling
if((keys.ArrowUp||keys.KeyW)&&hero.jump===0){hero.jv=-600;hero.jump=-1}if(hero.jump!==0){hero.jv+=1500*dt;hero.jump+=hero.jv*dt;if(hero.jump>=0){hero.jump=0;hero.jv=0}}
hero.x=clamp(hero.x+ix*355*dt,180,1100);let h,y,spr;if(half){const q=p/.52;h=lerp(205,105,ease(q));y=lerp(560,335,ease(q))+hero.jump;spr=hero.jump<0?anim('runJump',.11):anim('runBack',.095)}else{const q=(p-.52)/.48;h=lerp(120,225,ease(q));y=lerp(360,570,ease(q))+hero.jump;spr=hero.jump<0?anim('runJump',.11):anim('runFront',.095);drawSprite(im('boss'),640,lerp(155,210,q),lerp(95,430,q*q),.98)}drawSprite(spr,hero.x,y,h);updateEnemies(dt,'air');updateCombat(dt,'up');drawEnemies();if(Math.abs(p-.52)<.018){ctx.fillStyle='rgba(0,0,0,.6)';ctx.fillRect(480,75,320,42);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='900 20px Arial';ctx.fillText('TURN — FACE IT.',640,103)}}
function transition2(dt){const p=local(4,5);drawCover(im('runway'),0,0,W,H,1.03);ctx.save();ctx.globalAlpha=1-p*.8;drawSprite(anim('runFront',.09),lerp(580,650,p),560,210);ctx.restore();drawSprite(im('pianoBoost',Math.floor(p*3)%3),lerp(1150,650,ease(p)),560,lerp(120,235,p));ctx.fillStyle='#fff';ctx.font='900 20px Arial';ctx.textAlign='center';ctx.fillText(p<.55?'HOLD ↑ / W — CALL THE GRAND':'JUMP ON.',640,660)}
function roadPoint(z,lane,curve){const maxZ=1800,zz=clamp(z/maxZ,0,1),pers=1-zz,horizon=245,roadHalf=lerp(520,60,zz),cy=horizon+pers*430,cx=640+Math.sin((clock*0.35+z*.0015))*120*(1-zz)+curve*90*(1-zz);return{x:cx+lane*roadHalf*.52,y:cy,scale:lerp(1,.13,zz),half:roadHalf}}
function drawRoad(){drawCover(im('maze'),0,0,W,H,1.02,cam.x*.3,0);const horizon=240;ctx.fillStyle='rgba(5,10,16,.88)';ctx.beginPath();ctx.moveTo(120,H);ctx.lineTo(575,horizon);ctx.lineTo(705,horizon);ctx.lineTo(1160,H);ctx.closePath();ctx.fill();ctx.strokeStyle='#4cccf7';ctx.globalAlpha=.35;ctx.lineWidth=3;ctx.stroke();ctx.globalAlpha=1;for(let i=0;i<20;i++){let z=((i*120+(clock-cues[5])*330)%2400);const a=roadPoint(z,0,0),b=roadPoint(z+55,0,0);ctx.strokeStyle=i%2?'#fff':'#7ce7ff';ctx.globalAlpha=.45*(1-z/2400);ctx.lineWidth=Math.max(1,6*a.scale);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}ctx.globalAlpha=1}
function maze(dt){const p=local(5,6),ix=inputX(),iy=inputY();cam.tx=ix*44;cam.ty=iy*-12;cam.tz=vehicle.air>0?.90:1;camera(dt);drawRoad();vehicle.vx=lerp(vehicle.vx,ix*390,.08);vehicle.x=clamp(vehicle.x+vehicle.vx*dt,210,1070);vehicle.y=clamp(vehicle.y+iy*180*dt,475,635);if(vehicle.air>0){vehicle.av+=1450*dt;vehicle.air+=vehicle.av*dt;if(vehicle.air>=0){vehicle.air=0;vehicle.av=0}}routeObjects.forEach(o=>{o.z-=340*dt;const pt=roadPoint(o.z,o.lane,o.curve);if(o.z>50&&o.z<1800){if(o.type==='ramp'){const ri=Math.abs(o.lane)%M.ramps.length;drawSprite(im('ramps',ri),pt.x,pt.y,130*pt.scale);if(Math.abs(pt.x-vehicle.x)<85&&Math.abs(pt.y-vehicle.y)<70&&o.z<360&&vehicle.air===0){vehicle.air=-1;vehicle.av=-670;score+=500}}else if(o.type==='enemy'){drawSprite(im('routeEnemies',Math.abs(o.lane+2)%M.routeEnemies.length),pt.x,pt.y,150*pt.scale)}else{ctx.fillStyle='rgba(50,215,255,.45)';ctx.fillRect(pt.x-55*pt.scale,pt.y-30*pt.scale,110*pt.scale,60*pt.scale)}}});routeObjects=routeObjects.filter(o=>o.z>-200);while(routeObjects.length<18){const last=Math.max(...routeObjects.map(o=>o.z),400);routeObjects.push({z:last+rand(220,330),type:Math.random()<.28?'ramp':Math.random()<.55?'enemy':'gate',lane:[-1,0,1][Math.floor(Math.random()*3)],curve:rand(-1,1)})}const state=vehicle.air<0?'pianoBoost':ix<-.2?'pianoLeft':ix>.2?'pianoRight':keys.Space?'pianoFire':'pianoDrive';drawSprite(im(state,Math.floor(clock*8)%M[state].length),vehicle.x,vehicle.y+vehicle.air,195);updateEnemies(dt,'air');updateCombat(dt,'up');drawEnemies();ctx.fillStyle='#73e8ff';ctx.font='800 13px Arial';ctx.textAlign='center';ctx.fillText(vehicle.air<0?'AIRTIME ×2':'THE GRAND — ALGORITHM ROUTE',640,695)}
function transition3(dt){const p=local(6,7);drawCover(im('maze'),0,0,W,H,lerp(1,.9,p));const y=lerp(565,350,ease(p));drawSprite(im('pianoBoost',2),640,y,lerp(210,155,p));ctx.strokeStyle=`rgba(90,225,255,${1-p})`;ctx.lineWidth=6;ctx.beginPath();ctx.arc(640,330,80+p*380,0,7);ctx.stroke();ctx.fillStyle='#fff';ctx.font='900 20px Arial';ctx.textAlign='center';ctx.fillText('DON’T STOP — ENTER THE STORM',640,660)}
function bossScene(dt){const p=local(7,8),lost=1-boss.hp/boss.max;floorBroken=floorBroken||lost>.33||p>.36;const omin=ease(clamp((p-.05)/.82,0,1));cam.tx=inputX()*24;cam.ty=0;cam.tz=lerp(.88,1.12,omin);camera(dt);drawCover(im('bossBg'),0,0,W,H,cam.zoom,cam.x,0);boss.x=640+Math.sin(clock*.55)*150;boss.y=145+Math.sin(clock*.9)*18;drawSprite(im('boss'),boss.x,boss.y,lerp(245,430,omin));if(!floorBroken){ctx.fillStyle='#111820';ctx.fillRect(0,570,W,150);ctx.strokeStyle='#4ecff8';ctx.globalAlpha=.45;ctx.beginPath();ctx.moveTo(0,570);ctx.lineTo(W,570);ctx.stroke();ctx.globalAlpha=1;hero.y=570+hero.jump}else{platforms.forEach((pl,i)=>{const float=Math.sin(clock*1.2+i)*7;drawSprite(im('platforms',i%M.platforms.length),pl.x,pl.y+float,95);});let nearest=platforms.reduce((a,b)=>Math.abs(b.x-hero.x)<Math.abs(a.x-hero.x)?b:a,platforms[0]);hero.y=nearest.y-80+hero.jump}if((keys.ArrowUp||keys.KeyW)&&hero.jump===0){hero.jv=-580;hero.jump=-1}if(hero.jump!==0){hero.jv+=1450*dt;hero.jump+=hero.jv*dt;if(hero.jump>=0){hero.jump=0;hero.jv=0}}hero.x=clamp(hero.x+inputX()*345*dt,120,1160);const state=hero.jump<0?'aimJump':keys.Space?'aimFire':'aimIdle';drawSprite(im(state,Math.floor(clock*9)%M[state].length),hero.x,hero.y,205);updateEnemies(dt,'air');updateCombat(dt,'up');drawEnemies();if(p>.92&&boss.hp>7)boss.hp-=dt*.9}
function finale(dt){const p=local(8,9);const z=lerp(1.08,.62,ease(p));drawCover(im('bossBg'),0,0,W,H,z);drawSprite(im('boss'),640,245,lerp(400,170,p),1-p*.55);drawSprite(im('aimFire',Math.floor(clock*10)%M.aimFire.length),640,585,180);finalCharge=clamp(finalCharge+((keys.Space||keys.ArrowUp||keys.KeyW)?dt*.9:dt*.18),0,1);ctx.strokeStyle='#73e9ff';ctx.lineWidth=8;ctx.beginPath();ctx.arc(640,380,60+finalCharge*220,0,Math.PI*2);ctx.stroke();if(p>.72){ctx.fillStyle=`rgba(255,255,255,${clamp((p-.72)/.28,0,.85)})`;ctx.fillRect(0,0,W,H)}ctx.fillStyle='#fff';ctx.font='900 20px Arial';ctx.textAlign='center';ctx.fillText('HOLD FIRE — RELEASE THE SIGNAL',640,670)}
function ending(){drawCover(im('bossBg'),0,0,W,H,.62);ctx.fillStyle='rgba(0,0,0,.62)';ctx.fillRect(0,0,W,H);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='900 54px Arial';ctx.fillText('THE SIGNAL SURVIVES.',640,315);ctx.fillStyle='#78e7ff';ctx.font='700 19px Arial';ctx.fillText('AN ALGORITHM CAN PREDICT A CHOICE. IT CANNOT OWN ONE.',640,365)}
function hud(){ctx.fillStyle='rgba(2,7,12,.84)';ctx.fillRect(24,18,470,105);ctx.fillStyle='#fff';ctx.font='900 24px Arial';ctx.textAlign='left';ctx.fillText('RETURN OF THE AVIATOR',38,48);ctx.fillStyle='#64dcff';ctx.font='700 14px Arial';ctx.fillText(clock>cues[2]?'808 BOOMER // BASS PRESSURE':'TONEARM // WHOLE NOTE',38,78);ctx.fillStyle=audioStatus.startsWith('PLAYING')?'#82efc4':'#ffb36b';ctx.fillText('♫ TOO FAST • '+audioStatus,255,78);ctx.fillStyle='#a6b6c5';ctx.fillText(`SCORE ${String(Math.floor(score)).padStart(7,'0')}  COMBO x${combo}`,38,105);if(scene==='boss'){ctx.fillStyle='rgba(0,0,0,.7)';ctx.fillRect(380,18,520,14);ctx.fillStyle='#ff5148';ctx.fillRect(380,18,520*clamp(boss.hp/boss.max,0,1),14)}if(debug){ctx.fillStyle='rgba(0,0,0,.78)';ctx.fillRect(1040,18,220,118);ctx.fillStyle='#8be7ff';ctx.font='12px monospace';ctx.fillText(`SCENE ${scene}`,1053,40);ctx.fillText(`CLOCK ${clock.toFixed(1)} / ${totalDur.toFixed(1)}`,1053,58);ctx.fillText(`BOTS ${enemies.length}`,1053,76);ctx.fillText(`SHOTS ${shots.length}/${enemyShots.length}`,1053,94);ctx.fillText(`CAM ${cam.zoom.toFixed(2)}`,1053,112)}}
let dtGlobal=0;function loop(now){if(!started)return;const dt=Math.min(.033,(now-last)/1000||0);dtGlobal=dt;last=now;clock+=dt;sceneLocal+=dt;setScene(sceneFor(clock));ctx.clearRect(0,0,W,H);if(scene==='intro')intro(dt);else if(scene==='dive')dive(dt);else if(scene==='t1')transition1(dt);else if(scene==='runway')runway(dt);else if(scene==='t2')transition2(dt);else if(scene==='maze')maze(dt);else if(scene==='t3')transition3(dt);else if(scene==='boss')bossScene(dt);else if(scene==='finale')finale(dt);else ending();hud();requestAnimationFrame(loop)}
loadAll().then(m=>{const b=document.getElementById('start');b.disabled=false;b.textContent=m?`START EXPERIENCE (${m} OPTIONAL ASSETS MISSING)`:'START EXPERIENCE';if(new URLSearchParams(location.search).get('autostart')==='1')start()}).catch(e=>{fatal.style.display='block';fatal.textContent='LOAD ERROR: '+e.message});document.getElementById('start').addEventListener('click',start);
})();
