'use strict';
const demoVerses = [
 ['Last train, back row, I was writing in the dark','Beat tapped on the glass, now the whole car sparks','Sneakers on the pavement, got a drum beneath my feet','Turn a cracked-up sidewalk to a sample for the street','Corner store closing, still the cypher at the door','Kick-snare from a bucket got the block asking for more','No label on the jacket, just a verse and a view','Pass the mic across the city, let the next voice come through'],
 ['Pen hit the paper, had the bassline in my head','Three words on a napkin, now the whole page is red','I was rhyming through the rain by the busted windowpane','Made a hook out of the struggle, let it loop through the pain','Doubt stood by the door, I told that doubt to take a seat','Every setback got chopped into a break beneath the beat','Eight bars on the page, hear the room begin to move','Hand the verse to the next one, let them find a different groove'],
 ['Kitchen clock ticking, so I rapped against the time','My brother hit the table, kept the pocket for the rhyme','Radio full of static, found a break inside the noise','Two chairs made a stage, we let the whole room hear our voice','Neighbor knocked the wall, then he clapped along in four','Bass came through the floorboards, had a crowd outside the door','No spotlight in the kitchen, still the flow was running free','One mic passed in a circle, everybody got sixteen']
];
const states = {start:{role:'odd',bars:[],archive:[{bars:demoVerses[1].map(text=>({text,by:'demo'})),demo:true}],draft:''},continue:{role:'even',bars:[{text:demoVerses[0][0],by:'demo'}],archive:[{bars:demoVerses[2].map(text=>({text,by:'demo'})),demo:true}],draft:''}};
const esc = s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const words = s=>(s.toLowerCase().match(/[a-z]+(?:'[a-z]+)?/g)||[]);
const lastWord = s=>words(s).at(-1)||'';
function syllables(s){return words(s).reduce((n,w)=>n+Math.max(1,(w.replace(/(?:[^laeiouy]es|ed|[^laeiouy]e)$/,'').match(/[aeiouy]+/g)||[]).length),0)}
const families = [['night','light','bright','sight','write','right','flight','white','fight'],['street','feet','beat','heat','meet','seat','repeat'],['time','rhyme','climb','prime','chime'],['room','bloom','gloom','tomb'],['rain','again','pain','train','brain','chain'],['you','new','through','blue','true','view','too','do'],['wall','fall','call','all','tall'],['door','doors','floor','floors','more','shore'],['name','flame','game','same'],['free','me','be','sea','see','tree']];
function rhymeKey(w){const f=families.findIndex(a=>a.includes(w));return f<0?'~'+w.slice(-3):String(f)}
function rhymes(a,b){return a!==b&&a.length>1&&b.length>1&&rhymeKey(a)===rhymeKey(b)}
const themes={'City & movement':['city','street','train','sneakers','corner','road','night','lights','bus'],'Growth & resilience':['hope','dream','dreams','bloom','seed','storm','rain','fall','rise','scars','scar','doubts','light'],'Music & connection':['rhythm','rhyme','beat','brother','song','radio','sound','voice','room','mic','music']};
function analyze(bars){const texts=bars.map(b=>b.text),all=words(texts.join(' '));const ranks=Object.entries(themes).map(([name,terms])=>({name,hits:all.filter(w=>terms.includes(w)).length})).sort((a,b)=>b.hits-a.hits);const ends=texts.map(lastWord);let pairs=[];for(let i=0;i<ends.length;i++)for(let j=i+1;j<ends.length;j++)if(rhymes(ends[i],ends[j]))pairs.push([i+1,j+1]);const counts=texts.map(syllables),spread=counts.length?Math.max(...counts)-Math.min(...counts):0;return {theme:ranks[0].hits?ranks[0].name:'Open / emerging',pairs,counts,spread,ends,strength:!bars.length?'Waiting for ink':bars.length===1?'An opening':pairs.length&&spread<=4?'Finding a pocket':pairs.length?'Rhyme taking shape':'Free-form so far',continuity:!bars.length?'Not yet established':ranks[0].hits>=3?'Shared imagery':bars.length<3?'Still developing':'Loose thread'}}
function summary(bars){const a=analyze(bars);if(!bars.length)return 'Your first bar sets the direction. Rhyme is optional; leave the next voice something to build on.';return `${bars.length===8?'Eight bars complete. ':''}${a.theme==='Open / emerging'?'The theme is still open.':`The imagery suggests ${a.theme.toLowerCase()}.`} ${a.pairs.length?`Possible end-rhyme links: ${a.pairs.slice(0,3).map(p=>p.join('–')).join(', ')}.`:'No clear end-rhyme link detected yet.'} ${a.counts.length>1?`About ${Math.min(...a.counts)}–${Math.max(...a.counts)} syllables per bar; ${a.spread>4?'try reading the longer lines aloud.':'a fairly even line length.'}`:'Let the next voice answer.'}`}
function isYours(s){return s.bars.length<8&&(s.role==='odd'?s.bars.length%2===0:s.bars.length%2===1)}
function barHTML(b,i,latest){return `<div class="bar ${latest?'latest':''}"><span class="number">${String(i+1).padStart(2,'0')}</span><span>${esc(b.text)}</span><span class="by">${b.by==='you'?'YOU':'DEMO'}</span></div>`}
function renderLane(id,scroll=true){const s=states[id],n=s.bars.length,own=isYours(s),complete=n===8,a=analyze(s.bars);let lane=document.getElementById('lane-'+id);if(!lane){lane=document.createElement('section');lane.id='lane-'+id;lane.className='lane '+id;lane.setAttribute('aria-label',id==='start'?'Start a Verse':'Continue a Verse');document.getElementById('lanes').append(lane)}
lane.innerHTML=`<div class="lane-head"><div><h2>${id==='start'?'Start a Verse':'Continue a Verse'}</h2><p>${id==='start'?'Set it off. You write the odd bars.':'Catch the thread. You write the even bars.'}</p></div><span class="lane-icon" aria-hidden="true">${id==='start'?'+':'↳'}</span></div><div class="progress-row"><b>${n} / 8 BARS</b><div class="segments" aria-label="${n} of 8 bars complete">${Array.from({length:8},(_,i)=>`<span class="segment ${i<n?'done':''}"></span>`).join('')}</div><span>${s.role.toUpperCase()} LINES</span></div><div class="history-toolbar"><span>THE INFINITE SCROLL</span><button class="jump" data-action="jump">Jump to current ↓</button></div><div class="scroll" tabindex="0" aria-label="${id} full verse history">${s.archive.map((v,i)=>`<article class="archive"><div class="stanza-label"><span>STANZA ${String(i+1).padStart(3,'0')}</span><span>${v.demo?'DEMO ARCHIVE':'COMPLETE'} · 8/8</span></div>${v.bars.map((b,j)=>barHTML(b,j,false)).join('')}<details><summary>Eight-bar review</summary>${esc(summary(v.bars))}</details></article>`).join('')}<article class="current"><div class="stanza-label"><span>STANZA ${String(s.archive.length+1).padStart(3,'0')}</span><span>${complete?'COMPLETE':n?'IN PROGRESS':'OPEN MIC'}</span></div>${n?s.bars.map((b,i)=>barHTML(b,i,i===n-1)).join(''):'<div class="empty"><span class="empty-number">01</span><h3>Every verse starts somewhere.</h3><p>Give the next voice a world to step into.<br>The opening bar is yours.</p></div>'}</article></div><div class="composer"><div class="composer-label"><label for="input-${id}">${complete?'Eight down. Keep it going.':own?`Your turn · bar ${n+1}`:`Mic passed · bar ${n+1}`}</label><span class="muted" id="count-${id}">${s.draft.length}/160</span></div><textarea id="input-${id}" rows="2" maxlength="160" ${!own?'disabled':''} placeholder="${complete?'A whole stanza, made together.':own?(n?'Pick up the last line and make it yours…':'Drop the first bar…'):'Your demo partner has the mic…'}">${esc(s.draft)}</textarea><div class="draft-guide" id="guide-${id}">${guide(s)}</div><div class="actions"><span class="turn-hint">${complete?'Stanza review is ready below.':own?'One bar. Make it yours.':'Next voice: demo partner'}</span>${complete?'<button class="new" data-action="new">Next stanza ↗</button>':own?`<button class="submit" data-action="submit" ${!s.draft.trim()?'disabled':''}>Drop bar &nbsp; ↗</button>`:'<button class="partner" data-action="partner">Let demo partner respond</button>'}</div></div><div class="analyzer"><div class="analyzer-head"><b>✧ &nbsp; ${complete?'STANZA REVIEW':'LIVING ANALYZER'}</b><span>LOCAL ESTIMATES</span></div><div class="metrics"><div class="metric"><span>Strength</span><strong>${a.strength}</strong></div><div class="metric"><span>Continuity</span><strong>${a.continuity}</strong></div><div class="metric"><span>Theme</span><strong>${a.theme}</strong></div></div><p class="analysis-text">${esc(summary(s.bars))}</p></div>`;
lane.querySelector('textarea').addEventListener('input',e=>{s.draft=e.target.value;document.getElementById('count-'+id).textContent=s.draft.length+'/160';document.getElementById('guide-'+id).textContent=guide(s);lane.querySelector('.submit').disabled=!s.draft.trim();const draftBars=[...s.bars,{text:s.draft,by:'you'}];lane.querySelector('.analysis-text').textContent=s.draft.trim()?'Draft preview: '+summary(draftBars):summary(s.bars)});
lane.querySelector('textarea').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();if(s.draft.trim())submit(id,s.draft)}});
lane.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>{const action=b.dataset.action;if(action==='jump')jump(id);if(action==='submit')submit(id,s.draft);if(action==='partner')partner(id);if(action==='new')nextStanza(id)}));if(scroll)jump(id,false)}
function guide(s){if(!s.draft.trim()){const end=s.bars.length?lastWord(s.bars.at(-1).text):'';return end?`Last word: “${end}” · Rhyme or take a new direction.`:'No fixed scheme. Your first line sets the tone.'}const end=lastWord(s.draft),previous=s.bars.map(b=>lastWord(b.text));return `≈ ${syllables(s.draft)} syllables · ${previous.some(w=>rhymes(w,end))?'Possible rhyme connection':previous.length?'No clear end rhyme — still welcome':'Opening sound: '+end}`}
function jump(id,smooth=true){const box=document.querySelector('#lane-'+id+' .scroll');const bars=box.querySelectorAll('.current .bar');const target=bars.length?bars[Math.max(0,bars.length-4)]:box.querySelector('.current');box.scrollTo({top:target.getBoundingClientRect().top-box.getBoundingClientRect().top+box.scrollTop-10,behavior:smooth&&!matchMedia('(prefers-reduced-motion: reduce)').matches?'smooth':'instant'})}
function announce(message){document.getElementById('announcement').textContent=message}
function submit(id,text){const s=states[id];if(!s||!isYours(s))throw new Error('It is not your turn.');if(typeof text!=='string'||!text.trim()||text.trim().length>160||/[\r\n]/.test(text.trim())){announce('Use one non-empty line, up to 160 characters.');document.getElementById('guide-'+id).textContent='Use one line, up to 160 characters.';return {error:'Use one line, up to 160 characters.'}}s.bars.push({text:text.trim(),by:'you'});s.draft='';renderLane(id);announce(s.bars.length===8?'Eight bars complete. Your stanza review is ready.':'Bar added. Your demo partner has the mic.');return {barCount:s.bars.length,complete:s.bars.length===8}}
function response(s){const a=analyze(s.bars),last=lastWord(s.bars.at(-1)?.text||''),bank=demoVerses.flat(),used=s.bars.map(b=>b.text),match=bank.filter(t=>rhymes(last,lastWord(t))&&!used.includes(t));if(match.length)return match[Math.floor(Math.random()*match.length)];const pool=demoVerses[a.theme==='Music & connection'?2:a.theme==='Growth & resilience'?1:0].filter(t=>!used.includes(t));return pool[Math.floor(Math.random()*pool.length)]||'Another voice arrives to carry this along'}
function partner(id){const s=states[id];if(!s||isYours(s)||s.bars.length===8)return;s.bars.push({text:response(s),by:'demo'});renderLane(id);announce(s.bars.length===8?'Eight bars complete. Your stanza review is ready.':`Demo partner added bar ${s.bars.length}. Your turn.`);if(isYours(s))document.getElementById('input-'+id).focus({preventScroll:true})}
function nextStanza(id){const s=states[id];if(s.bars.length!==8)return;s.archive.push({bars:s.bars.map(b=>({...b})),demo:false});s.bars=id==='start'?[]:[{text:demoVerses[(s.archive.length)%3][0],by:'demo'}];renderLane(id);document.getElementById('input-'+id).focus({preventScroll:true});announce('New stanza ready. Your previous stanza is in the scroll.')}
let excerptIndex=-1;
function shuffle(){const cuts=demoVerses.flatMap((v,i)=>[0,4].map(start=>({bars:v.slice(start,start+4),source:'DEMO ARCHIVE · '+String(i+1).padStart(3,'0')})));Object.values(states).forEach(s=>{s.archive.filter(v=>!v.demo).forEach(v=>[0,4].forEach(start=>cuts.push({bars:v.bars.slice(start,start+4).map(b=>b.text),source:'YOUR SESSION'})));if(s.bars.length===8)[0,4].forEach(start=>cuts.push({bars:s.bars.slice(start,start+4).map(b=>b.text),source:'YOUR SESSION'}))});let i=Math.floor(Math.random()*cuts.length);if(i===excerptIndex)i=(i+1)%cuts.length;excerptIndex=i;document.getElementById('excerpt').innerHTML=cuts[i].bars.map(t=>`<p>${esc(t)}</p>`).join('');document.getElementById('excerpt-source').textContent=cuts[i].source}
document.getElementById('shuffle').addEventListener('click',shuffle);document.getElementById('how').addEventListener('click',()=>{const el=document.getElementById('instructions');el.hidden=!el.hidden;document.getElementById('how').setAttribute('aria-expanded',String(!el.hidden))});document.getElementById('how').setAttribute('aria-expanded','false');document.getElementById('how').setAttribute('aria-controls','instructions');Object.keys(states).forEach(id=>renderLane(id));shuffle();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'submit_bar',description:'Submit one bar to the selected lane on the user’s turn. The demo partner then takes the next turn.',inputSchema:{type:'object',properties:{lane:{type:'string',enum:['start','continue']},text:{type:'string',minLength:1,maxLength:160}},required:['lane','text'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||!['start','continue'].includes(input.lane))throw new Error('Choose start or continue.');return submit(input.lane,input.text)}})).catch(()=>{})}catch{}}
