import * as T from '../vendor/three.module.js';
import {createRangeArt} from './art.js';
import {WEAPONS,newRun,multiplier,accuracy,rank,award,seeded,intersectDisc} from './rules.mjs';
const $=id=>document.getElementById(id),canvas=$('game');
let renderer;try{renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});}catch(e){$('error').hidden=false;$('error').textContent='WebGL is unavailable. Enable browser hardware acceleration and reload.';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.65));renderer.setClearColor(0x091420);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;
const scene=new T.Scene();scene.fog=new T.FogExp2(0x091420,.022);const camera=new T.PerspectiveCamera(60,1,.04,100);camera.position.set(0,2.8,6);camera.rotation.order='YXZ';scene.add(camera);
const art=createRangeArt(T,renderer,scene,camera);
const {weaponRoot,models,mesh,box,cyl,ring}=art;
const {dark,steel,black}=art.materials;
const {cyan,red:pink,amber:warm}=art.lights;
let active=0,state='menu',run=newRun(),slots=[],targets=[],fx=[],yaw=0,pitch=0,held=false,ads=false,kick=0,last=performance.now(),rng=seeded(Date.now()),spawnClock=0,calloutTime=0,feedbackTime=0,hitTime=0,swapTime=0,ready=true;const keys=new Set();let best=0;try{best=Number(localStorage.getItem('gb.range.best.v2'))||0;}catch{}
const music=new Audio('assets/music/audio/Guns and Butter 3.mp3');music.loop=true;music.volume=.35;let audio,master;const preferences={music:.35,fx:.65,sensitivity:1,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches};$('reduced-motion').checked=preferences.reduced;
function unlock(){try{audio??=new (window.AudioContext||window.webkitAudioContext)();if(!master){master=audio.createGain();master.gain.value=preferences.fx;master.connect(audio.destination);}audio.resume().catch(()=>{});}catch{}music.play().catch(()=>{});}
function tone(freq,duration=.1,type='sine',volume=.2,slide=1){if(!audio||!master)return;const o=audio.createOscillator(),a=audio.createGain(),t=audio.currentTime;o.type=type;o.frequency.setValueAtTime(freq,t);o.frequency.exponentialRampToValueAtTime(Math.max(20,freq*slide),t+duration);a.gain.setValueAtTime(volume,t);a.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(a);a.connect(master);o.start();o.stop(t+duration);o.onended=()=>{o.disconnect();a.disconnect();};}
function soundShot(){if(active===0){tone(330,.14,'sawtooth',.15,.22);tone(990,.07,'triangle',.08,.5);}else if(active===1){tone(1800,.045,'square',.045,.35);tone(420,.075,'triangle',.12,.6);}else{tone(125,.45,'sine',.6,.26);tone(68,.3,'triangle',.2,.5);}}
function select(i){active=i;models.forEach((m,n)=>m.g.visible=n===i);document.querySelectorAll('.card').forEach((el,n)=>{el.classList.toggle('active',n===i);el.setAttribute('aria-pressed',String(n===i));el.querySelector('.check').textContent=n===i?'●':'○';});swapTime=.25;kick=.05;$('weapon-name').textContent=WEAPONS[i].name;$('weapon-type').textContent=WEAPONS[i].tag;}
WEAPONS.forEach((w,i)=>{const b=document.createElement('button');b.className='card';b.innerHTML=`<span class="number">0${i+1}</span><span><b>${w.name}</b><small>${w.tag}</small></span><span class="check"></span>`;b.onclick=()=>select(i);$('cards').append(b);});select(0);
function announce(a,b){$('callout-title').textContent=a;$('callout-sub').textContent=b;calloutTime=2.6;}
function feedback(s){$('feedback').textContent=s;feedbackTime=.85;}
function dispose(o){o.traverse(c=>{if(c.geometry)c.geometry.dispose();if(c.userData.ownMaterial)c.material.dispose();});o.removeFromParent();}
const targetMats={normal:cyan,bonus:warm,hazard:pink,armor:steel};let serial=0;
function spawn(){const stage=run.stage,r=rng();const type=r<.14?'hazard':r<.27?'bonus':r<.43&&stage>0?'armor':'normal';let x,y,z;for(let a=0;a<15;a++){x=(rng()-.5)*15;y=1.5+rng()*3.8;z=-8-rng()*17;if(targets.every(t=>Math.hypot((x-t.x)/(6-z)*23,(y-t.y)/(6-z)*23)>2.1))break;}
 const radius=type==='bonus'?.56:type==='armor'?.92:.79,{g,body,holes}=art.makeTarget(type,radius,y);scene.add(g);g.position.set(x,y,z);const hp=type==='armor'?145:type==='bonus'?35:70;targets.push({id:serial++,x,y,z,baseX:x,baseY:y,radius,type,hp,maxHp:hp,age:0,life:Math.max(4.5,9-stage*1.4),phase:rng()*6.28,speed:stage?(.55+rng()*.7)*stage:0,g,body,holes,dead:false});}

function clearRange(){targets.forEach(t=>dispose(t.g));targets=[];fx.forEach(f=>dispose(f.o));fx=[];}
function start(){clearRange();run=newRun($('mode').value==='practice');slots=WEAPONS.map(w=>({ammo:w.ammo,reload:0,cooldown:0}));rng=seeded(Date.now());yaw=pitch=0;held=ads=false;kick=0;spawnClock=0;state='playing';$('menu').hidden=true;$('results').hidden=true;$('pause-panel').hidden=true;$('hud').hidden=false;for(let i=0;i<6;i++)spawn();select(active);announce('01 / SOUNDCHECK','CYAN RECORDS = POINTS · RED × = HAZARD');unlock();}
function pause(){if(state!=='playing')return;state='paused';held=ads=false;keys.clear();$('pause-panel').hidden=false;document.exitPointerLock?.();music.pause();}
function resume(){state='playing';$('pause-panel').hidden=true;held=false;unlock();}
function menu(){state='menu';held=false;keys.clear();$('menu').hidden=false;$('hud').hidden=true;$('results').hidden=true;$('pause-panel').hidden=true;clearRange();document.exitPointerLock?.();music.pause();$('record').textContent=best?`PERSONAL BEST / ${best.toLocaleString()} POINTS`:'YOUR NEXT HIGH SCORE STARTS HERE';}
function finish(){state='results';held=false;keys.clear();document.exitPointerLock?.();$('hud').hidden=true;$('results').hidden=false;const isBest=run.score>best;if(isBest&&!run.practice){best=run.score;try{localStorage.setItem('gb.range.best.v2',String(best));}catch{}}const [grade,name]=rank(run.score);$('medal').textContent=grade;$('rank').textContent=name;$('final-score').textContent=run.score.toLocaleString();$('result-eyebrow').textContent=isBest?'NEW PERSONAL BEST':'SESSION COMPLETE';$('result-message').textContent=grade==='S'?'You own the stage. Can you do it again?':'Keep your streak alive. Hit the center. Chase the next rank.';$('result-stats').innerHTML=`<div><b>${accuracy(run)}%</b>ACCURACY</div><div><b>${run.broken}</b>BROKEN</div><div><b>${run.maxStreak}</b>BEST STREAK</div><div><b>${run.shots}</b>SHOTS</div><div><b>${run.bullseyes}</b>BULLSEYES</div><div><b>${run.hazards}</b>HAZARDS</div>`;tone(523,.15);tone(784,.4,'triangle',.1);}
function reload(){if(state!=='playing')return;const s=slots[active],w=WEAPONS[active];if(s.reload||s.ammo===w.ammo)return;s.reload=w.reload;held=false;feedback('RELOADING THE MIX');tone(180,.08,'triangle',.15,2);}
function aimPoint(){camera.updateMatrixWorld();const o=camera.getWorldPosition(new T.Vector3()),d=camera.getWorldDirection(new T.Vector3());const hit=intersectDisc(o,d,targets);return hit?new T.Vector3(hit.point.x,hit.point.y,hit.point.z):o.addScaledVector(d,Math.max(5,(-32-o.z)/d.z));}
function orient(){camera.rotation.set(pitch,yaw,0);camera.updateMatrixWorld();weaponRoot.position.set(ads?.19:.35,(ads?-.29:-.39)-(slots[active]?.reload?Math.sin(slots[active].reload/WEAPONS[active].reload*Math.PI)*.35:0),-1.13+kick*.5);const aim=aimPoint();weaponRoot.lookAt(aim);weaponRoot.updateMatrixWorld(true);for(const b of models[active].barrels){b.lookAt(aim);b.updateMatrixWorld(true);}return aim;}
function transient(o,life,update){fx.push({o,life,max:life,update});}
function beam(from,to,color,width=1){
 const index=active,dir=to.clone().sub(from),length=dir.length();
 const geo=new T.BufferGeometry().setFromPoints([from,to]);
 const material=new T.LineBasicMaterial({color:index===2?0xf2b67b:index===0?0xafdbe0:0xeed2a0,transparent:true,opacity:.24,depthWrite:false,blending:T.AdditiveBlending});
 const line=new T.Line(geo,material);line.userData.ownMaterial=true;scene.add(line);transient(line,.085,(o,t)=>o.material.opacity=t*.24);
 const projectile=art.projectile(scene,from,to,index),flight=Math.min(.16,length/180);transient(projectile,flight,(o,t)=>{o.position.copy(from).addScaledVector(dir,1-t);if(index===0)o.rotateZ(.5);});
}
function burst(p,color,heavy=false){
 for(let i=0;i<(preferences.reduced?5:heavy?22:12);i++){
  const o=mesh(new T.SphereGeometry(.015,6,4),warm,scene);o.scale.set(1,1,4);o.position.copy(p);o.castShadow=false;const v=new T.Vector3((rng()-.5)*5,rng()*4,(rng()-.5)*4+2);
  transient(o,.2+rng()*.35,(obj,t,dt)=>{obj.position.addScaledVector(v,dt);v.y-=8*dt;obj.lookAt(obj.position.clone().add(v));obj.scale.set(t,t,t*5);});
 }
 for(let i=0;i<4;i++){
  const mat=new T.MeshStandardMaterial({color:0x8b8980,transparent:true,opacity:.16,roughness:1,depthWrite:false});
  const o=mesh(new T.SphereGeometry(.06,10,6),mat,scene,[p.x,p.y,p.z+.05]);o.userData.ownMaterial=true;o.castShadow=false;const velocity=new T.Vector3((rng()-.5)*.5,.15+rng()*.3,.2);
  transient(o,.65,(obj,t,dt)=>{obj.position.addScaledVector(velocity,dt);obj.scale.setScalar(1+(1-t)*3);obj.material.opacity=t*.13;});
 }
 if(heavy){for(let j=0;j<3;j++){const mat=new T.MeshBasicMaterial({color:0xeac19a,transparent:true,opacity:.35,depthWrite:false});const o=ring(scene,mat,.16,.008,p.x,p.y,p.z+.1+j*.06);o.userData.ownMaterial=true;o.castShadow=false;transient(o,.35+j*.08,(obj,t)=>{obj.scale.setScalar(1+(1-t)*(12+j*3));obj.material.opacity=t*.3;});}}
}
let lastShot=null;
function fire(){if(state!=='playing'||swapTime>0)return;const w=WEAPONS[active],s=slots[active];if(s.reload||s.cooldown>0)return;if(s.ammo<=0){reload();return;}const aim=orient(),model=models[active],barrelIndex=active===0?(w.ammo-s.ammo)%2:0,muzzle=model.muzzles[barrelIndex].getWorldPosition(new T.Vector3()),forward=model.muzzles[barrelIndex].getWorldDirection(new T.Vector3());s.ammo--;s.cooldown=w.cooldown;run.shots++;soundShot();const events={kills:0,bullseye:false,bonus:false,hazard:false,hit:false};const touched=new Set();const damage=(t,value,bullseye=false)=>{if(t.dead)return;if(t.type==='hazard'){events.hazard=true;t.hp=0;}else{events.hit=true;events.bonus ||= t.type==='bonus';events.bullseye ||= bullseye;t.hp-=value*(bullseye?1.4:1);}if(t.hp<=0){t.dead=true;t.g.visible=false;if(t.type!=='hazard')events.kills++;burst(new T.Vector3(t.x,t.y,t.z),t.type==='hazard'?0xff788c:0xffd45c);}};
 let mainEnd=aim.clone();for(let i=0;i<w.pellets;i++){const end=aim.clone();if(i){const a=(i-1)*Math.PI/2,r=muzzle.distanceTo(aim)*w.spread*(ads?.55:1);end.x+=Math.cos(a)*r;end.y+=Math.sin(a)*r;}const dir=end.clone().sub(muzzle).normalize(),hit=intersectDisc(muzzle,dir,targets);if(hit){end.set(hit.point.x,hit.point.y,hit.point.z);art.markHit(hit.target,hit.point);damage(hit.target,w.damage,hit.bullseye);touched.add(hit.target);}if(!i)mainEnd=end.clone();beam(muzzle,end,w.color,active===2?3:1);if(active===2&&hit){for(const t of targets){if(!t.dead&&!touched.has(t)&&new T.Vector3(t.x,t.y,t.z).distanceTo(end)<2.5){damage(t,85);touched.add(t);}}burst(end,w.color,true);}}
 const flash=art.muzzleFlash(scene,muzzle,forward,active);transient(flash,.075,(o,t)=>o.scale.setScalar(t));lastShot={weapon:w.id,muzzle:muzzle.toArray(),forward:forward.toArray(),aim:aim.toArray(),end:mainEnd.toArray(),barrelIndex};kick=preferences.reduced?0:w.kick;const points=award(run,events);if(events.hazard){feedback('−200 / WRONG RECORD');tone(85,.2,'sawtooth',.1,.5);}else if(events.hit){feedback(`${events.bullseye?'BULLSEYE / ':events.bonus?'GOLD RECORD / ':''}+${points}${events.kills>1?' · MULTI BREAK':''}`);hitTime=.17;tone(events.bullseye?1100:740,.07,'sine',.12);}else feedback('MISS / FIND THE GROOVE');if(!s.ammo)feedbackTime=Math.max(feedbackTime,1);}
const clamp=T.MathUtils.clamp;
function update(dt){kick*=Math.exp(-dt*15);swapTime=Math.max(0,swapTime-dt);calloutTime=Math.max(0,calloutTime-dt);feedbackTime=Math.max(0,feedbackTime-dt);hitTime=Math.max(0,hitTime-dt);
 if(state==='playing'){run.time+=dt;if(!run.practice&&run.time>=75){finish();return;}const stage=Math.min(2,Math.floor(run.time/25));if(stage!==run.stage){run.stage=stage;announce(stage===1?'02 / HEAVY ROTATION':'03 / ENCORE',stage===1?'MOVING RECORDS · ARMORED TARGETS':'FASTER TARGETS · MAKE IT COUNT');}for(let i=0;i<3;i++){const s=slots[i];s.cooldown=Math.max(0,s.cooldown-dt);if(s.reload){s.reload=Math.max(0,s.reload-dt);if(!s.reload){s.ammo=WEAPONS[i].ammo;if(i===active)tone(620,.08,'triangle',.08);}}}
 const sensitivity=preferences.sensitivity*(ads?.4:1);yaw=clamp(yaw+((keys.has('ArrowLeft')?1:0)-(keys.has('ArrowRight')?1:0))*dt*.7*sensitivity,-.63,.63);pitch=clamp(pitch+((keys.has('ArrowUp')?1:0)-(keys.has('ArrowDown')?1:0))*dt*.5*sensitivity,-.25,.3);
 if(run.time-run.lastHit>3.5)run.streak=0;for(const t of targets){t.age+=dt;if(t.dead)continue;if(t.age>t.life){t.dead=true;t.g.visible=false;if(t.type!=='hazard'){run.streak=0;run.expired++;}continue;}t.x=t.baseX+Math.sin(t.phase+t.age*t.speed)*(.6+run.stage*.3);t.y=t.baseY+Math.sin(t.phase+t.age*t.speed*.7)*run.stage*.13;t.g.position.set(t.x,t.y,t.z);t.g.scale.lerp(new T.Vector3(1,1,1),Math.min(1,dt*12));}
 for(let i=targets.length-1;i>=0;i--)if(targets[i].dead){dispose(targets[i].g);targets.splice(i,1);}spawnClock-=dt;if(targets.length<6+run.stage&&spawnClock<=0){spawn();spawnClock=.38;}orient();if(held&&active===1)fire();
 }else if(state==='menu'){camera.rotation.set(-.015,Math.sin(performance.now()*.00013)*.08,0);weaponRoot.visible=false;}weaponRoot.visible=state!=='menu';
 if(state==='playing')art.updateArt(run.time,active,slots[active]?.reload||0,kick,preferences.reduced);
 if(state==='playing'){const effectDt=Math.min(dt,.05);for(let i=fx.length-1;i>=0;i--){const f=fx[i];f.life-=effectDt;if(f.life<=0){dispose(f.o);fx.splice(i,1);}else f.update?.(f.o,f.life/f.max,effectDt);}}
 $('callout').style.opacity=calloutTime>0?Math.min(1,calloutTime):0;$('feedback').style.opacity=feedbackTime>0?1:0;$('hitmarker').style.opacity=hitTime>0?1:0;
 if(state==='playing'){const s=slots[active],w=WEAPONS[active];$('score').textContent=String(run.score).padStart(6,'0');$('best').textContent=`BEST ${best.toLocaleString()}`;$('timer').textContent=run.practice?'∞':Math.max(0,75-run.time).toFixed(1);$('stage').textContent=['01 / SOUNDCHECK','02 / HEAVY ROTATION','03 / ENCORE'][run.stage];$('time-bar').style.width=`${run.practice?100:(75-run.time)/.75}%`;$('combo').textContent=`×${multiplier(run.streak)}`;$('streak').textContent=run.streak?`${run.streak} HIT STREAK`:'BUILD YOUR STREAK';$('combo-bar').style.width=`${Math.max(0,1-(run.time-run.lastHit)/3.5)*100}%`;$('ammo').textContent=String(s.ammo).padStart(2,'0');$('ammo-label').textContent=s.reload?'RELOADING':s.ammo?`/ ${w.ammo} · ${active===1?'HOLD TO FIRE':'CLICK TO FIRE'}`:'R / RELOAD';$('reload-bar').style.width=`${s.reload?(1-s.reload/w.reload)*100:0}%`;$('accuracy').textContent=`${accuracy(run)}%`;}
}
function resize(){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();}addEventListener('resize',resize);resize();
function frame(now){const dt=Math.max(0,(now-last)/1000);last=now;update(dt);renderer.render(scene,camera);requestAnimationFrame(frame);}requestAnimationFrame(frame);
$('start').disabled=false;$('start').textContent='DROP INTO THE RANGE →';$('start').onclick=start;$('replay').onclick=start;$('restart').onclick=start;$('resume').onclick=resume;$('pause').onclick=pause;$('quit').onclick=menu;$('loadout').onclick=menu;
for(const type of ['help','settings'])$(type+'-open').onclick=()=>$(type+'-dialog').showModal();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('music-volume').oninput=e=>{preferences.music=Number(e.target.value);music.volume=preferences.music;};$('fx-volume').oninput=e=>{preferences.fx=Number(e.target.value);if(master)master.gain.value=preferences.fx;};$('sensitivity').oninput=e=>preferences.sensitivity=Number(e.target.value);$('reduced-motion').onchange=e=>preferences.reduced=e.target.checked;
canvas.addEventListener('pointermove',e=>{if(state!=='playing'||e.pointerType==='touch')return;if(document.pointerLockElement===canvas){yaw=clamp(yaw-e.movementX*.0018*preferences.sensitivity*(ads?.4:1),-.63,.63);pitch=clamp(pitch-e.movementY*.0018*preferences.sensitivity*(ads?.4:1),-.25,.3);}else{yaw=clamp((.5-e.clientX/innerWidth)*1.12,-.63,.63);pitch=clamp((.5-e.clientY/innerHeight)*.52,-.25,.3);}});
canvas.addEventListener('pointerdown',e=>{if(state!=='playing'||e.pointerType==='touch')return;if(e.button===2){ads=true;return;}if(e.button===0){held=true;fire();}});addEventListener('pointerup',()=>{held=false;ads=false;});canvas.oncontextmenu=e=>e.preventDefault();
let touch=null;canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'&&state==='playing'){touch={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);}});canvas.addEventListener('pointermove',e=>{if(!touch||touch.id!==e.pointerId||state!=='playing')return;yaw=clamp(yaw-(e.clientX-touch.x)*.003*preferences.sensitivity,-.63,.63);pitch=clamp(pitch-(e.clientY-touch.y)*.003*preferences.sensitivity,-.25,.3);touch.x=e.clientX;touch.y=e.clientY;});canvas.addEventListener('pointerup',()=>touch=null);canvas.addEventListener('pointercancel',()=>{touch=null;held=false;});
$('touch-fire').onpointerdown=e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);held=true;fire();};$('touch-fire').onpointerup=()=>held=false;$('touch-fire').onpointercancel=()=>held=false;$('touch-reload').onclick=reload;$('touch-swap').onclick=()=>{if(state==='playing')select((active+1)%3);};
addEventListener('keydown',e=>{if(e.target.matches('input,select,button')&&e.code!=='Escape')return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='Escape'){if(state==='playing')pause();return;}if(state!=='playing')return;keys.add(e.code);if(e.repeat)return;if(e.code==='KeyR')reload();if(/^Digit[123]$/.test(e.code))select(Number(e.code.slice(-1))-1);if(e.code==='Space'){held=true;fire();}if(e.code==='KeyP'){try{const p=canvas.requestPointerLock();p?.catch(()=>feedback('POINTER LOCK UNAVAILABLE · MOUSE AIM STILL WORKS'));}catch{feedback('USE MOUSE AIM');}}});addEventListener('keyup',e=>{keys.delete(e.code);if(e.code==='Space')held=false;});addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});document.addEventListener('pointerlockchange',()=>{if(!document.pointerLockElement&&state==='playing')pause();});
// Read-only diagnostics for QA, never a scoring/cheat control surface.
window.WOMP={snapshot:()=>({state,active,run:{...run},slots:slots.map(s=>({...s})),targets:targets.map(t=>({id:t.id,x:t.x,y:t.y,z:t.z,radius:t.radius,type:t.type,hp:t.hp,dead:t.dead})),lastShot,audio:{state:audio?.state,musicPaused:music.paused,musicTime:music.currentTime},render:renderer.info.render}),project:(x,y,z)=>{const v=new T.Vector3(x,y,z).project(camera);return {x:(v.x+1)*innerWidth/2,y:(1-v.y)*innerHeight/2};}};
menu();

