const canvas=document.getElementById('streamsCanvas'),ctx=canvas.getContext('2d');
const ui={intro:introOverlay,end:endOverlay,penny:pennyCount,attention:attentionCount,current:currentLabel,progress:progressFill,endTitle,endSummary,endMessage,toast};
const music=document.getElementById('music');music.volume=.32;
let W=0,H=0,dpr=1,run=false,last=0,elapsed=0,cameraY=0,keys={left:false,right:false,jump:false};
let player,platforms=[],coins=[],orbs=[],spray=[],ripples=[],pennies=0,attention=0,stageY=-2600;
const mediaTypes=['VINYL','CASSETTE','PHONE','MIC','MPC','SPEAKER','KEYBOARD','CAMERA','CD','TABLET'];
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=canvas.clientWidth;H=canvas.clientHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
function reset(){pennies=attention=elapsed=cameraY=0;player={x:W*.5-18,y:H*.76,vx:0,vy:0,w:36,h:66,onGround:false,headScale:1};platforms=[];coins=[];orbs=[];spray=[];ripples=[];for(let i=0;i<42;i++){const anchor=i%9===0,size=Math.random(),w=size<.14?230:size<.42?155:95+Math.random()*45;platforms.push({x:24+Math.random()*Math.max(40,W-w-48),y:H*.83-i*(92+Math.random()*22),w,h:22,type:mediaTypes[i%mediaTypes.length],anchor,drift:(Math.random()-.5)*.32})}stageY=platforms.at(-1).y-120;updateHUD()}
function currentStrength(){const p=Math.min(elapsed/155,1);return Math.max(.9,1.35+p*2.25+Math.max(0,attention-pennies)*.035-Math.min(pennies*.025,.6))}
function updateHUD(){ui.penny.textContent=pennies;ui.attention.textContent=attention;const r=currentStrength();ui.current.textContent=r<1.9?'CALM':r<2.7?'PUSHING':r<3.5?'STRONG':'RUSHING';const prog=Math.max(0,Math.min(1,(H*.76-(player.y-cameraY))/(H*.76-(stageY-cameraY))));ui.progress.style.height=prog*100+'%'}
function spawn(){const top=cameraY-100;if(Math.random()<.032)coins.push({x:20+Math.random()*(W-40),y:top,r:9,spin:Math.random()*6});if(Math.random()<.018+Math.min(pennies*.0008,.012)){const r=Math.random(),size=r<.12?3:r<.38?2:1;orbs.push({x:20+Math.random()*(W-40),y:top-20,size,r:12*size,val:size===1?1:size===2?3:7,rot:0})}}
function collide(p){return player.x+player.w>p.x&&player.x<p.x+p.w&&player.y+player.h>=p.y&&player.y+player.h<=p.y+32&&player.vy>=0}
function hit(o){return Math.hypot(o.x-(player.x+player.w/2),o.y-(player.y+18))<o.r+24*player.headScale}
function showToast(t){ui.toast.textContent=t;ui.toast.classList.add('show');clearTimeout(ui.toast._t);ui.toast._t=setTimeout(()=>ui.toast.classList.remove('show'),650)}
function update(dt){elapsed+=dt/60;const current=currentStrength();player.vx+=(keys.left?-.55:keys.right?.55:0)*dt;player.vx*=Math.pow(.88,dt);player.x+=player.vx*dt/(1+(player.headScale-1)*.75);player.x=Math.max(0,Math.min(W-player.w,player.x));player.vy+=.55*dt;player.y+=player.vy*dt+current*.13*dt;player.onGround=false;for(const p of platforms){if(!p.anchor)p.y+=current*.38*dt;p.x+=p.drift*dt;if(p.x<0||p.x+p.w>W)p.drift*=-1;if(collide(p)){player.y=p.y-player.h;player.vy=0;player.onGround=true;if(keys.jump){player.vy=-12.2/current**.07;player.onGround=false;ripples.push({x:player.x+player.w/2,y:p.y,life:34})}}}cameraY+=(player.y-H*.64-cameraY)*.05;spawn();for(const c of coins){c.y+=current*1.5*dt;c.spin+=.08*dt}for(const o of orbs){o.y+=current*2*dt;o.rot+=.05*dt}coins=coins.filter(c=>{if(hit(c)){pennies++;showToast('+1 VALUE');for(let i=0;i<8;i++)spray.push({x:c.x,y:c.y,vx:(Math.random()-.5)*2,vy:-Math.random()*2.5,life:30});return false}return c.y-cameraY<H+80});orbs=orbs.filter(o=>{if(hit(o)){attention+=o.val;showToast('+'+o.val+' ATTENTION');return false}return o.y-cameraY<H+100});player.headScale=1+Math.min(Math.max(attention-pennies,0)*.028,.55);for(const s of spray){s.x+=s.vx*dt;s.y+=s.vy*dt;s.vy+=.08*dt;s.life-=dt}spray=spray.filter(s=>s.life>0);ripples.forEach(r=>r.life-=dt);ripples=ripples.filter(r=>r.life>0);if(player.y-cameraY>H+80)finish(false);if(player.y<stageY+50)finish(true);updateHUD()}
function drawRiver(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#c9f4f5');g.addColorStop(.45,'#3aaeb6');g.addColorStop(1,'#073b46');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(let i=0;i<18;i++){const x=(i*63+elapsed*7)%W;ctx.strokeStyle=`rgba(255,255,255,${.08+(i%3)*.025})`;ctx.lineWidth=1.2+(i%2);ctx.beginPath();ctx.moveTo(x,0);for(let y=0;y<H+80;y+=40)ctx.lineTo(x+Math.sin((y+elapsed*18+i*15)*.025)*18,y);ctx.stroke()}const lip=H-56,vg=ctx.createLinearGradient(0,lip,0,H);vg.addColorStop(0,'rgba(255,255,255,.15)');vg.addColorStop(1,'rgba(2,20,25,.88)');ctx.fillStyle=vg;ctx.fillRect(0,lip,W,56);for(let i=0;i<40;i++){ctx.fillStyle='rgba(255,255,255,.28)';ctx.fillRect((i*37+elapsed*28)%W,lip+Math.sin(i)*8,2,25)}}
function drawStage(){const y=stageY-cameraY;ctx.fillStyle='#111';ctx.fillRect(W*.22,y,W*.56,18);ctx.fillStyle='#222';ctx.fillRect(W*.28,y-70,W*.44,70);ctx.fillStyle='#fff';ctx.font='900 18px Arial';ctx.textAlign='center';ctx.fillText('STAGE',W/2,y-28)}
function drawPlatforms(){for(const p of platforms){const sy=p.y-cameraY;if(sy<-80||sy>H+80)continue;ctx.save();ctx.translate(p.x+p.w/2,sy+p.h/2);ctx.fillStyle=p.anchor?'#473c35':'#efe8dc';ctx.shadowColor='rgba(0,0,0,.35)';ctx.shadowBlur=12;ctx.fillRect(-p.w/2,-p.h/2,p.w,p.h);ctx.shadowBlur=0;ctx.fillStyle=p.anchor?'#fff':'#111';ctx.font='900 11px Arial';ctx.textAlign='center';ctx.fillText(p.type,0,4);if(p.anchor){ctx.fillStyle='#c47f3b';ctx.fillRect(-4,p.h/2,8,16)}ctx.restore()}}
function drawCoins(){for(const c of coins){const y=c.y-cameraY;ctx.save();ctx.translate(c.x,y);ctx.scale(Math.abs(Math.sin(c.spin))+.15,1);ctx.fillStyle='#b76b29';ctx.beginPath();ctx.arc(0,0,c.r,0,7);ctx.fill();ctx.fillStyle='#ffd89b';ctx.font='900 12px Arial';ctx.textAlign='center';ctx.fillText('¢',0,4);ctx.restore()}}
function drawOrbs(){for(const o of orbs){const y=o.y-cameraY;ctx.save();ctx.translate(o.x,y);ctx.rotate(o.rot);ctx.fillStyle='#1877d1';ctx.shadowColor='rgba(24,119,209,.7)';ctx.shadowBlur=15;ctx.beginPath();ctx.arc(0,0,o.r,0,7);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#fff';ctx.lineWidth=Math.max(2,o.size);ctx.beginPath();ctx.moveTo(-o.r*.35,-o.r*.35);ctx.lineTo(o.r*.35,o.r*.35);ctx.moveTo(o.r*.35,-o.r*.35);ctx.lineTo(-o.r*.35,o.r*.35);ctx.stroke();ctx.restore()}}
function drawPlayer(){const sy=player.y-cameraY;ctx.save();ctx.translate(player.x+player.w/2,sy);ctx.fillStyle='#1b1d1f';ctx.fillRect(-13,28,26,38);ctx.fillStyle='#39271f';ctx.beginPath();ctx.arc(0,18,17*player.headScale,0,7);ctx.fill();ctx.fillStyle='#111';ctx.fillRect(-10,6,20,7);ctx.strokeStyle='#e5e5e5';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(-8,66);ctx.lineTo(-11,82);ctx.moveTo(8,66);ctx.lineTo(12,82);ctx.stroke();ctx.restore()}
function drawEffects(){for(const r of ripples){const a=r.life/34;ctx.strokeStyle=`rgba(255,255,255,${a*.55})`;ctx.beginPath();ctx.ellipse(r.x,r.y-cameraY,(34-r.life)*1.5,(34-r.life)*.55,0,0,7);ctx.stroke()}for(const s of spray){ctx.fillStyle=`rgba(255,222,160,${s.life/30})`;ctx.fillRect(s.x,s.y-cameraY,2,2)}}
function draw(){ctx.clearRect(0,0,W,H);drawRiver();drawStage();drawPlatforms();drawCoins();drawOrbs();drawEffects();drawPlayer();const v=ctx.createRadialGradient(W/2,H*.5,Math.min(W,H)*.18,W/2,H*.5,Math.max(W,H)*.72);v.addColorStop(0,'rgba(0,0,0,0)');v.addColorStop(1,'rgba(0,0,0,.5)');ctx.fillStyle=v;ctx.fillRect(0,0,W,H)}
function loop(t){if(!run)return;const dt=Math.min((t-last)/16.67,2);last=t;update(dt);draw();requestAnimationFrame(loop)}
function finish(win){if(!run)return;run=false;music.pause();ui.end.classList.remove('hidden');ui.endTitle.textContent=win?'YOU REACHED THE STAGE.':'AAAAAAAHHHHH! · SPLASH!';ui.endSummary.textContent=`Pennies: ${pennies} · Attention: ${attention}`;ui.endMessage.textContent=win?(pennies>attention?'Whew. You barely created more value than attention.':'You arrived—but attention still outweighed value.'):'The current carried everything over the edge. Attention can move fast. Value helps you choose the direction.'}
startBtn.onclick=()=>{ui.intro.classList.add('hidden');reset();run=true;music.currentTime=0;music.play().catch(()=>{});last=performance.now();requestAnimationFrame(loop)};exitBtn.onclick=()=>parent.postMessage('closeExperience','*');addEventListener('keydown',e=>{if(e.key==='ArrowLeft')keys.left=true;if(e.key==='ArrowRight')keys.right=true;if(e.code==='Space')keys.jump=true});addEventListener('keyup',e=>{if(e.key==='ArrowLeft')keys.left=false;if(e.key==='ArrowRight')keys.right=false;if(e.code==='Space')keys.jump=false});function hold(id,key){const el=document.getElementById(id);el.onpointerdown=()=>keys[key]=true;el.onpointerup=el.onpointerleave=()=>keys[key]=false}hold('leftBtn','left');hold('rightBtn','right');hold('jumpBtn','jump');reset();draw();
