import {BurstPool} from './variation.js';
export const BURSTS={release:{reveal:[0,.24,.52],duration:1.65,line:'The work is yours. The flight is not.',title:'The release'},apex:{reveal:[0,.48,.98],duration:2.65,line:'Stillness is a point inside the motion.',title:'Out of your hands'},catch:{reveal:[0,.32,.72],duration:2.15,line:'The return asks you to be present.',title:'Back with you'}};
export class ReelTimeline {
 constructor(){this.reset()}
 reset(){this.active=null;this.elapsed=0;this.revealed=0;this.seen=new Set();this.completed=[];this.events=[];}
 start(phase,attempt,quality=0){const key=`${attempt}:${phase}`;if(this.active||this.seen.has(key)||!BURSTS[phase])return false;this.seen.add(key);this.active={phase,attempt,quality,key};this.elapsed=0;this.revealed=0;this.events.push({type:'open',...this.active});this.step(0);return true;}
 step(dt){if(!this.active)return;this.elapsed+=Math.max(0,Math.min(dt,.05));const profile=BURSTS[this.active.phase];while(this.revealed<3&&this.elapsed>=profile.reveal[this.revealed])this.events.push({type:'reveal',...this.active,index:this.revealed++});if(this.elapsed>=profile.duration){const done=this.active;this.completed.push(done.key);this.active=null;this.events.push({type:'close',...done});}}
 drain(){const out=this.events;this.events=[];return out;}
 snapshot(){return {active:this.active?.phase??null,elapsed:this.elapsed,revealed:this.revealed,completed:[...this.completed]};}
}

export class PhotoReel {
 constructor(audio,onCapture,onClose){this.audio=audio;this.onCapture=onCapture;this.onClose=onClose;this.timeline=new ReelTimeline();this.library=null;this.archive=[];this.favorites=new Set();this.galleryOpen=false;this.lastFocus=null;this.session=Date.now().toString(36);try{const saved=JSON.parse(localStorage.getItem('iwa-photo-favorites')||'[]');if(Array.isArray(saved))this.favorites=new Set(saved.filter(x=>typeof x==='string').slice(0,30));}catch{}this.root=document.getElementById('photo-cutaway');this.gallery=document.getElementById('photo-gallery');this.strip=document.getElementById('photo-tiles');this.lastShot=null;}
 async load(){const r=await fetch('assets/photo-reel/library.json');if(!r.ok)throw Error('Photo library unavailable');this.library=await r.json();this.selectors=Object.fromEntries(Object.keys(this.library.pools).map(p=>[p,new BurstPool()]));this.decoded=await Promise.all([...new Set(Object.values(this.library.pools).flat().map(s=>s.src))].map(async src=>{const image=new Image();image.src=src;await image.decode();return image}));}
 reset(){this.timeline.reset();this.archive=[];this.session=Date.now().toString(36);this.lastShot=null;this.root.classList.add('hidden');this.closeGallery();document.body.classList.remove('photo-active');}
 start(phase,attempt,quality){if(!this.timeline.start(phase,attempt,quality))return false;const order={preparation:0,release:1,post_release:2,catch_ready:0,tracking:0,catch:1,landing:2,secured:3};this.shots=this.selectors[phase].pick(this.library.pools[phase],phase).sort((a,b)=>(order[a.category]??1)-(order[b.category]??1));return true;}
 get active(){return !!this.timeline.active}
 update(dt){this.timeline.step(dt);for(const event of this.timeline.drain()){
  if(event.type==='open'){this.root.className=`photo-cutaway ${event.phase}`;document.body.classList.add('photo-active');this.root.setAttribute('aria-label',BURSTS[event.phase].title);document.getElementById('photo-title').textContent=BURSTS[event.phase].title;document.getElementById('photo-line').textContent=BURSTS[event.phase].line;document.getElementById('photo-quality').textContent=event.quality>.94?'A moment worth keeping':'A study in motion';this.strip.replaceChildren();for(const [i,shot] of this.shots.entries()){const figure=document.createElement('figure');figure.className=`photo-tile crop-${shot.crop}`;figure.style.aspectRatio=shot.width+"/"+shot.height;const img=new Image();img.src=shot.src;img.alt=shot.alt;const caption=document.createElement('figcaption');caption.textContent=`0${i+1} / ${shot.label}`;figure.append(img,caption);this.strip.append(figure);}}
  if(event.type==='reveal'){this.strip.children[event.index]?.classList.add('revealed');this.audio.shutter(event.phase,event.index);this.onCapture(event.phase);const asset=this.shots[event.index];const shot={...asset,id:`${this.session}-${event.key}-${event.index}`,phase:event.phase,attempt:event.attempt,best:event.index===1&&event.quality>.9};this.archive.push(shot);if(this.archive.length>90)this.archive.shift();this.lastShot=shot;}
  if(event.type==='close'){this.root.classList.add('hidden');document.body.classList.remove('photo-active');this.onClose(event.phase);}
 }}
 saveFavorites(){try{localStorage.setItem('iwa-photo-favorites',JSON.stringify([...this.favorites]));}catch{}}
 favoriteBest(){const best=[...this.archive].reverse().find(s=>s.best)||this.lastShot;if(best){this.favorites.add(best.asset);this.saveFavorites();}return best;}
 openGallery(){this.lastFocus=document.activeElement;this.galleryOpen=true;this.gallery.classList.remove('hidden');this.renderGallery();document.getElementById('gallery-close').focus();}
 closeGallery(){this.galleryOpen=false;this.gallery.classList.add('hidden');this.lastFocus?.focus?.();}
 renderGallery(){const grid=document.getElementById('gallery-grid');grid.replaceChildren();document.getElementById('gallery-count').textContent=`${this.archive.length} frames · ${this.archive.filter(s=>this.favorites.has(s.asset)).length} selected`;document.getElementById('gallery-empty').classList.toggle('hidden',this.archive.length>0);for(const shot of this.archive){const item=document.createElement('article');item.className='gallery-item';const img=new Image();img.src=shot.src;img.alt=shot.alt;img.loading='lazy';const p=document.createElement('p');p.textContent=`${shot.label} · Throw ${shot.attempt}${shot.best?' · Best shot':''}`;const button=document.createElement('button');const selected=this.favorites.has(shot.asset);button.textContent=selected?'♥ Selected':'♡ Keep this';button.setAttribute('aria-pressed',String(selected));button.onclick=()=>{if(this.favorites.has(shot.asset))this.favorites.delete(shot.asset);else this.favorites.add(shot.asset);this.saveFavorites();const index=[...grid.children].indexOf(item);this.renderGallery();grid.children[index]?.querySelector('button').focus();};item.append(img,p,button);grid.append(item);}}
 snapshot(){return {...this.timeline.snapshot(),gallery:this.galleryOpen,photos:this.archive.length,favorites:this.favorites.size,assets:this.shots?.map(s=>s.asset)??[],history:this.archive.map(s=>({attempt:s.attempt,phase:s.phase,asset:s.asset}))};}
}



