// Fixed offline bundle: no runtime imports, fetches, CDNs, or server required.
import {readFile,writeFile} from 'node:fs/promises';
const root=new URL('../',import.meta.url),read=p=>readFile(new URL(p,root),'utf8');
const three=await read('vendor/three.module.js');
const match=three.match(/export\s*\{([^}]+)\};?\s*$/);
if(!match)throw Error('Unexpected Three.js export format');
const entries=match[1].split(',').map(s=>{const parts=s.trim().split(/\s+as\s+/);return parts.length===2?`${parts[1]}:${parts[0]}`:parts[0];});
const vendor=three.slice(0,match.index);
const reference=(await read('src/reference-womps.js')).replace(/^export /gm,'');
const modules=await Promise.all(['palace.js','tempest.js','tempest-audio.js','tempest-museum.js'].map(p=>read('src/'+p)));
const museum=modules.map(code=>code.replace(/^import .*;\r?\n/gm,'').replace(/^export /gm,'')).join('\n');
const art=await Promise.all([1,2,3].map(async n=>'data:image/jpeg;base64,'+(await readFile(new URL(`assets/museum/black-art-0${n}.jpg`,root))).toString('base64')));
const pavilion={marble:'data:image/jpeg;base64,'+(await readFile(new URL('assets/pavilion/calacatta.jpg',root))).toString('base64'),garden:'data:image/jpeg;base64,'+(await readFile(new URL('assets/pavilion/garden.jpg',root))).toString('base64')};
await writeFile(new URL('src/museum.bundle.js',root),`/* Generated by tools/build-museum.mjs */\n(()=>{const T=(()=>{${vendor}\nreturn {${entries.join(',')}}})();\nconst MUSEUM_ART_DATA=${JSON.stringify(art)};\nconst PAVILION_DATA=${JSON.stringify(pavilion)};\n${reference}\n${museum}\n})();\n`);
console.log('Museum offline bundle built.');
