// Dependency-free bundler for this fixed, vendored module graph.
// Preserves Three.js's license header. Rebuild after editing src/ or vendor/.
import {readFile,writeFile} from 'node:fs/promises';
const root=new URL('../',import.meta.url);
const read=p=>readFile(new URL(p,root),'utf8');
const three=await read('vendor/three.module.js');
const match=three.match(/export\s*\{([^}]+)\};?\s*$/);
if(!match)throw Error('Unexpected Three.js export format');
const entries=match[1].split(',').map(s=>{const parts=s.trim().split(/\s+as\s+/);if(parts.some(p=>!/^[$\w]+$/.test(p)))throw Error('Unsupported export');return parts.length===2?`${parts[1]}:${parts[0]}`:parts[0];});
const vendor=three.slice(0,match.index);
if(/\bimport\s*[({*]/.test(vendor))throw Error('Vendor gained an external import');
const rules=(await read('src/rules.mjs')).replace(/^export /gm,'');
const replicas=(await read('src/reference-womps.js')).replace(/^export /gm,'');
const musicFx=(await read('src/music-fx.js')).replace(/^export /gm,'');
const art=(await read('src/art.js')).replace(/^export /gm,'').replace(/^import .*;\r?\n/gm,'');
const game=(await read('src/range.js')).replace(/^import .*;\r?\n/gm,'');
await writeFile(new URL('src/range.bundle.js',root),`/* Generated by tools/build-offline.mjs. */\n(()=>{\nconst T=(()=>{\n${vendor}\nreturn {${entries.join(',')}};\n})();\n${rules}\n${replicas}\n${musicFx}\n${art}\n${game}\n})();\n`);
console.log('Offline classic-script bundle built.');
