const fs=require('fs'),vm=require('vm'),assert=require('assert');
const source=fs.readFileSync(process.argv[2],'utf8');let now=0;const nodes=new Map();const noop=()=>{};function node(sel){if(!nodes.has(sel))nodes.set(sel,{clientWidth:1280,clientHeight:800,style:{},classList:{add:noop,remove:noop},addEventListener:noop,play:()=>Promise.resolve(),getContext:()=>new Proxy({},{get:()=>noop})});return nodes.get(sel)}
const sandbox={console,Math,performance:{now:()=>now},document:{getElementById:node,querySelector:node,querySelectorAll:()=>[],addEventListener:noop},window:{addEventListener:noop},Image:class{set src(v){}},setTimeout:noop,requestAnimationFrame:noop};vm.createContext(sandbox);vm.runInContext(source,sandbox);
const run=s=>vm.runInContext(s,sandbox);run('reset()');
run(`const assert=(ok,msg)=>{if(!ok)throw Error(msg)};
reset();Keys.jumpPressed=true;update(1/120);assert(State.startRetired,'ledge retired');assert(!State.player.ground,'jump works');
reset();Keys.right=true;for(let i=0;i<12;i++)update(1/120);assert(State.player.vx>0,'right');Keys.right=false;Keys.left=true;for(let i=0;i<30;i++)update(1/120);assert(State.player.vx<0,'left');
reset();setDirection(1,true);setDirection(1,false);setDirection(1,true);assert(Keys.dashTimer>0,'dash');
reset();const q=State.platforms.find(q=>q.route&&!q.isStart&&q.spec.name!=='attentionBall');State.platforms=[q];q.kind='value';q.reward={type:'none',collected:true};function drop(){State.player.x=q.x+q.w/2-36;State.player.y=surfaceBounds(q).y-134;State.player.vy=120;State.player.ground=false;State.player.on=null;update(1/60);}drop();assert(State.player.on===q,'moving landing');const earned=State.value,streak=State.streak;drop();assert(State.value===earned&&State.streak===streak,'no farming');
for(const type of ['value','attention']){q.reward={type,tier:2,collected:false};State.player.x=q.x+q.w/2-36;State.player.y=surfaceBounds(q).y-132;State.player.ground=true;State.player.on=q;update(1/120);assert(q.reward.collected,type+' pickup');}
reset();const ball=State.platforms.find(q=>q.spec.name==='attentionBall');State.platforms=[ball];State.player.x=ball.x+ball.w/2-36;State.player.y=surfaceBounds(ball).y-134;State.player.vy=120;State.player.ground=false;State.player.on=null;update(1/60);assert(ball.springState==='compress','spring contact');Keys.jumpPressed=true;for(let i=0;i<28;i++)update(1/120);assert(State.player.vy < -600,'spring launch');assert(ball.perfectBounce,'perfect spring');
reset();State.player.ground=false;State.player.on=null;State.player.y=State.waterfallY+10;update(1/60);assert(State.endMode==='fail','fail');reset();assert(!State.endMode&&State.value===0&&!State.startRetired,'restart');
`);
console.log('PASS controls, dash, start retirement, moving landing, no farming, Value/Attention contact, perfect spring, fail/reset');
// Follow successive route surfaces using only direction and jump flags; no teleporting during traversal.
for(const width of [390,1280]){node('game').clientWidth=width;run('resize();reset()');let result=run(`(()=>{let target=null,landings=0,maxProgress=0,lastSeq=null,history=[];for(let f=0;f<120*240;f++){let p=State.player;maxProgress=Math.max(maxProgress,(State.startY-p.y)/5200);if(p.on&&p.on.puzzleSeq!==lastSeq){lastSeq=p.on.puzzleSeq;history.push(lastSeq);}if(State.endMode)return {mode:State.endMode,landings,progress:(State.startY-p.y)/5200,maxProgress,history:history.slice(-12)};if(p.ground){const options=State.platforms.filter(q=>!q.retired&&q!==p.on&&q.alpha>.1&&(q.kind==='stage'||q.route)&&surfaceBounds(q).y<surfaceBounds(p.on).y-20).sort((a,b)=>surfaceBounds(b).y-surfaceBounds(a).y);target=options[0];if(target){Keys.jumpPressed=true;landings++;}}if(target){let dx=target.x+target.w/2-(p.x+p.w/2);let brake=p.vx*.15;Keys.left=dx<brake-8;Keys.right=dx>brake+8;}update(1/120);}return {mode:'timeout',landings,y:State.player.y};})()`);console.log(width,result);}

