const canvas=document.getElementById('fireCanvas'),ctx=canvas.getContext('2d'),music=document.getElementById('music');music.volume=.34;
let W,H,dpr=1,run=false,angleIndex=0,questionIndex=0,timeLeft=0,totalTime=1,timerId=null,saved=[],lost=[],embers=[],smoke=[];
const ui={intro:introOverlay,end:endOverlay,title:promptTitle,hint:promptHint,timer:timerText,ring:timerRing,look:lookLabel,action:choiceAction,save:saveBtn,saved:savedSummary,lost:lostList,reflection};
const questions=[
{room:'LIVING ROOM',prompt:'The smoke is thick. You can save only one thing before the ceiling weakens.',hint:'Search the room. Two objects are still reachable.',options:[{name:'Family photo album',angle:1,type:'savable',symbol:'PHOTO'},{name:'Laptop',angle:5,type:'savable',symbol:'LAPTOP'},{name:'Wedding portrait',angle:3,type:'burning',symbol:'PORTRAIT'}]},
{room:'HALLWAY',prompt:'Your important document cabinet is on fire. Do you grab your documents or your car keys?',hint:'One is closer. One may matter more after you escape.',options:[{name:'Important documents',angle:2,type:'savable',symbol:'FILES'},{name:'Car keys',angle:6,type:'savable',symbol:'KEYS'},{name:'Document cabinet',angle:3,type:'burning',symbol:'CABINET'}]},
{room:'BEDROOM',prompt:'The room is filling fast. You hear glass breaking downstairs.',hint:'Three personal objects are visible, but only one can leave with you.',options:[{name:'Wedding ring',angle:0,type:'savable',symbol:'RING'},{name:'Journal',angle:4,type:'savable',symbol:'JOURNAL'},{name:'Baby picture',angle:7,type:'savable',symbol:'PICTURE'}]},
{room:'STUDIO',prompt:'Years of unfinished work are inside this room.',hint:'Some work can be recreated. Some memories cannot.',options:[{name:'External hard drive',angle:1,type:'savable',symbol:'DRIVE'},{name:'Microphone',angle:5,type:'savable',symbol:'MIC'},{name:'Lyric notebook',angle:7,type:'savable',symbol:'LYRICS'},{name:'Keyboard',angle:3,type:'burning',symbol:'KEYBOARD'}]},
{room:'OFFICE',prompt:'The exit is behind you. One final choice.',hint:'This room has fewer reachable items, so the decision window is shorter.',options:[{name:'Degree',angle:2,type:'savable',symbol:'DEGREE'},{name:'Business records',angle:6,type:'savable',symbol:'RECORDS'},{name:'Camera',angle:4,type:'burning',symbol:'CAMERA'}]}
];
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=canvas.clientWidth;H=canvas.clientHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
embers=Array.from({length:80},()=>({x:Math.random(),y:Math.random(),s:.5+Math.random()*2.2,v:.15+Math.random()*.7}));smoke=Array.from({length:24},()=>({x:Math.random(),y:Math.random(),r:40+Math.random()*90,v:.03+Math.random()*.08,a:.025+Math.random()*.06}));
const q=()=>questions[questionIndex],obj=()=>q().options.find(o=>o.angle===angleIndex)||null;
function calcTime(x){const reachable=x.options.filter(o=>o.type==='savable').length,dist=Math.max(...x.options.filter(o=>o.type==='savable').map(o=>Math.min(o.angle,8-o.angle)));return Math.max(5,Math.min(13,4+reachable*1.8+dist*.65))}
function startQuestion(){angleIndex=0;totalTime=calcTime(q());timeLeft=totalTime;ui.title.textContent=q().prompt;ui.hint.textContent=q().hint;updateView();clearInterval(timerId);timerId=setInterval(()=>{timeLeft-=.1;if(timeLeft<=0){timeLeft=0;timeoutQuestion()}updateTimer()},100)}
function updateTimer(){ui.timer.textContent=Math.ceil(timeLeft);ui.ring.style.setProperty('--time',Math.max(0,timeLeft/totalTime)*100+'%')}
function updateView(){ui.look.textContent=`${q().room} · VIEW ${angleIndex+1} OF 8`;const o=obj();if(o&&o.type==='savable'){ui.action.classList.add('show');ui.save.textContent=`SAVE ${o.name.toUpperCase()}`}else ui.action.classList.remove('show')}
function rotate(d){if(!run)return;angleIndex=(angleIndex+d+8)%8;updateView()}
function saveCurrent(){const o=obj();if(!o||o.type!=='savable')return;saved.push(o.name);q().options.filter(x=>x.name!==o.name).forEach(x=>lost.push(x.name));nextQuestion()}
function timeoutQuestion(){clearInterval(timerId);q().options.forEach(x=>lost.push(x.name));nextQuestion()}
function nextQuestion(){clearInterval(timerId);questionIndex++;if(questionIndex>=questions.length)return finish();startQuestion()}
function finish(){run=false;music.pause();ui.end.classList.remove('hidden');ui.saved.textContent=saved.length?`You saved: ${saved.join(' · ')}`:'You did not save any items.';ui.lost.innerHTML=[...new Set(lost)].map(x=>`<li>${x}</li>`).join('');ui.reflection.textContent='The experience is not measuring whether your choices were correct. It is revealing what became important when time, access, and certainty disappeared.'}
function drawObject(o,x,y,focus){ctx.save();ctx.translate(x,y);ctx.shadowColor=focus?'rgba(255,235,180,.8)':'rgba(255,80,20,.7)';ctx.shadowBlur=focus?18:8;ctx.fillStyle=focus?'#e9dfcc':'#5d3326';if(o.symbol==='KEYS'){ctx.strokeStyle='#e9dfcc';ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,15,0,7);ctx.stroke();ctx.fillRect(13,-4,34,8)}else if(o.symbol==='RING'){ctx.strokeStyle='#f2d7a1';ctx.lineWidth=8;ctx.beginPath();ctx.arc(0,0,22,0,7);ctx.stroke()}else if(o.symbol==='MIC'){ctx.fillRect(-8,-30,16,45);ctx.beginPath();ctx.arc(0,-35,13,0,7);ctx.fill()}else{ctx.fillRect(-42,-32,84,64);ctx.fillStyle='#111';ctx.font='900 10px Arial';ctx.textAlign='center';ctx.fillText(o.symbol,0,4)}ctx.restore()}
function assist(x,y,t){ctx.save();ctx.strokeStyle='rgba(255,245,210,.8)';ctx.lineWidth=2;const p=7+Math.sin(t*.006)*4;ctx.beginPath();ctx.moveTo(x-80-p,y);ctx.lineTo(x-48,y);ctx.moveTo(x+80+p,y);ctx.lineTo(x+48,y);ctx.stroke();ctx.fillStyle='#fff';for(let i=0;i<5;i++){const a=t*.002+i*1.25;ctx.fillRect(x+Math.cos(a)*58,y+Math.sin(a)*42,2,2)}ctx.restore()}
function flame(x,y,t){ctx.save();ctx.translate(x,y);for(let i=0;i<5;i++){ctx.fillStyle=`rgba(255,${80+i*25},20,.${25+i})`;ctx.beginPath();ctx.ellipse((i-2)*8,Math.sin(t*.01+i)*7,10,24+i*4,0,0,7);ctx.fill()}ctx.restore()}
function draw(t){const room=q()||questions.at(-1),g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,`hsl(${18+questionIndex*7},55%,10%)`);g.addColorStop(.55,`hsl(${12+questionIndex*7},45%,16%)`);g.addColorStop(1,'#050303');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='rgba(255,255,255,.035)';ctx.fillRect(0,H*.22,W,H*.56);ctx.strokeStyle='rgba(255,255,255,.08)';for(let i=0;i<12;i++){ctx.beginPath();ctx.moveTo(W/2,H*.48);ctx.lineTo(i*(W/11),H);ctx.stroke()}for(let y=H*.56;y<H;y+=42){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}const base=Math.sin(angleIndex/8*Math.PI*2);ctx.save();ctx.translate(W*.5,H*.58);ctx.fillStyle='rgba(20,14,10,.9)';if(room.room==='LIVING ROOM'){ctx.fillRect(-W*.32+base*40,20,W*.25,H*.16);ctx.fillRect(W*.08-base*30,0,W*.18,H*.22)}if(room.room==='HALLWAY'){ctx.fillRect(-W*.08,-H*.12,W*.16,H*.48);ctx.fillRect(-W*.35+base*60,30,W*.16,H*.24)}if(room.room==='BEDROOM'){ctx.fillRect(-W*.3,40,W*.42,H*.15);ctx.fillRect(W*.18,-20,W*.12,H*.28)}if(room.room==='STUDIO'){ctx.fillRect(-W*.35,35,W*.24,H*.16);ctx.fillRect(W*.1,-10,W*.25,H*.2)}if(room.room==='OFFICE'){ctx.fillRect(-W*.28,20,W*.3,H*.18);ctx.fillRect(W*.15,-40,W*.12,H*.3)}ctx.restore();const o=obj();if(o){const ox=W*.5+Math.sin(angleIndex/8*Math.PI*2)*W*.23,oy=H*.53+Math.cos(angleIndex/8*Math.PI*2)*40;if(o.type==='burning'){drawObject(o,ox,oy,false);flame(ox,oy-35,t)}else{ctx.save();ctx.globalAlpha=.28;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(ox,oy,68+Math.sin(t*.005)*7,0,7);ctx.fill();ctx.restore();drawObject(o,ox,oy,true);assist(ox,oy,t)}}const fg=ctx.createRadialGradient(W*.2,H*.72,10,W*.2,H*.72,W*.45);fg.addColorStop(0,'rgba(255,88,20,.35)');fg.addColorStop(1,'rgba(255,50,10,0)');ctx.fillStyle=fg;ctx.fillRect(0,0,W,H);for(const s of smoke){const x=(s.x*W+t*s.v*14)%W,y=(s.y*H-t*s.v*10+H)%H;ctx.fillStyle=`rgba(170,170,170,${s.a})`;ctx.beginPath();ctx.ellipse(x,y,s.r,s.r*.55,0,0,7);ctx.fill()}for(const e of embers){const x=e.x*W+Math.sin(t*.001+e.y*8)*12,y=H-((e.y*H+t*e.v*.08)%H);ctx.fillStyle=`rgba(255,174,70,${.28+e.s*.12})`;ctx.fillRect(x,y,e.s,e.s)}const v=ctx.createRadialGradient(W/2,H*.5,Math.min(W,H)*.14,W/2,H*.5,Math.max(W,H)*.7);v.addColorStop(0,'rgba(0,0,0,0)');v.addColorStop(1,'rgba(0,0,0,.78)');ctx.fillStyle=v;ctx.fillRect(0,0,W,H);requestAnimationFrame(draw)}requestAnimationFrame(draw);
startBtn.onclick=()=>{ui.intro.classList.add('hidden');run=true;questionIndex=0;saved=[];lost=[];music.currentTime=0;music.play().catch(()=>{});startQuestion()};leftBtn.onclick=()=>rotate(-1);rightBtn.onclick=()=>rotate(1);centerBtn.onclick=updateView;ui.save.onclick=saveCurrent;exitBtn.onclick=()=>parent.postMessage('closeExperience','*');addEventListener('keydown',e=>{if(e.key==='ArrowLeft')rotate(-1);if(e.key==='ArrowRight')rotate(1);if(e.code==='Space')saveCurrent()});
