// Run after shell or catalog changes: node scripts/build-seo.mjs
// Generated entry pages keep the existing app shell while exposing content before JavaScript.
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const write = (file, text) => fs.writeFileSync(path.join(root, file), text.replace(/[ \t]+$/gm, ''));
const base = 'https://2flykl.github.io/2flyKeithLogan/';
const esc = text => String(text || '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const projects = JSON.parse(read('data/projects.json'));
const playables = JSON.parse(read('data/playables-overhaul.json'));
const pages = {
  home: {file:'site-overhaul.html', title:'2Fly Keith Logan | Music, Films & Playable Experiences', heading:'2Fly Keith Logan', description:'Explore original music, films, documentaries and Playable Experiences by 2Fly Keith Logan. Enter the 2Fly Anti-Algorithm Experiment.'},
  featured: {file:'featured.html', title:'Featured Projects | 2Fly Keith Logan', heading:'Featured projects', description:'Discover featured music, films and interactive worlds by 2Fly Keith Logan, including Thru the Fire, Streams of Legacy and I Woke Up in Africa.'},
  playables: {file:'playables.html', title:'Playable Experiences | 2Fly Keith Logan', heading:'Playable Experiences', description:'Step inside the music and stories of 2Fly Keith Logan. Explore interactive experiences, music games and creative experiments in the Playables library.'},
  music: {file:'music-catalog.html', title:'Music & Albums | 2Fly Keith Logan', heading:'Music and albums by 2Fly Keith Logan', description:'Listen to original songs and explore albums by 2Fly Keith Logan, including Thru the Fire, Streams of Legacy, I Was Away and Artificial Love.'},
  videos: {file:'music-videos.html', title:'Music Videos & Films | 2Fly Keith Logan', heading:'Music videos and films', description:'Watch the visual stories of 2Fly Keith Logan. Explore music videos, project films and the I Woke Up in Africa documentary.'},
  flyzone: {file:'flyzone.html', title:'Flyzone Creative Studio | 2Fly Keith Logan', heading:'Welcome to the Flyzone', description:'Create in the room with 2Fly. Describe your musical idea, choose sounds and explore the Flyzone creative studio by 2Fly Keith Logan.'},
  africa: {file:'africa.html', title:'I Woke Up in Africa: The Project | 2Fly Keith Logan', heading:'I Woke Up in Africa', description:'Explore Keith Logan’s Rwanda journey through the I Woke Up in Africa documentary, soundtrack and connected Playable Experiences.'},
  support: {file:'support.html', title:'Help 2Fly Create | Support Independent Work', heading:'Help 2Fly create', description:'Support independent music, films, software and Playable Experiences by 2Fly Keith Logan. Experience the work and decide what it is worth to you.'}
};
const webSite = {'@type':'WebSite','@id':base+'#website',url:base+'pages/site-overhaul.html',name:'2Fly Keith Logan',alternateName:'2FLY',inLanguage:'en'};
const person = {'@type':'Person','@id':base+'#creator',name:'Keith Logan',alternateName:'2Fly Keith Logan',url:base+'pages/site-overhaul.html'};
for (const page of Object.values(pages)) {
  page.url = base + 'pages/' + page.file;
  page.schema = {'@context':'https://schema.org','@graph':[webSite,person,{'@type':'WebPage','@id':page.url+'#page',url:page.url,name:page.title,description:page.description,inLanguage:'en',isPartOf:{'@id':base+'#website'},about:{'@id':base+'#creator'}}]};
}
write('js/site-seo-pages.js', '// Generated by scripts/build-seo.mjs.\nwindow.SITE_SEO_PAGES = '+JSON.stringify(pages,null,2)+';\n');
const image = base+'assets/covers/thru-the-fire-cover.png';
function metadata(page) {
  return `<!-- SEO:start -->
  <title>${esc(page.title)}</title>
  <meta name="description" content="${esc(page.description)}">
  <link rel="canonical" href="${page.url}">
  <meta name="robots" content="index,follow,max-image-preview:large">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="2Fly Keith Logan">
  <meta property="og:title" content="${esc(page.title)}">
  <meta property="og:description" content="${esc(page.description)}">
  <meta property="og:url" content="${page.url}">
  <meta property="og:image" content="${image}">
  <meta property="og:image:alt" content="Thru the Fire — 2Fly Keith Logan cover artwork">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="${esc(page.title)}">
  <meta name="twitter:description" content="${esc(page.description)}">
  <meta name="twitter:image" content="${image}">
  <script type="application/ld+json" id="siteStructuredData">${JSON.stringify(page.schema).replace(/</g,'\\u003c')}</script>
  <!-- SEO:end -->`;
}
function entries(items, destination) {
  return items.map(p=>`<article><h2>${esc(p.title)}</h2><p>${esc(p.description || p.subtitle)}</p><a href="${esc(destination(p))}">Explore ${esc(p.title)}</a></article>`).join('\n');
}
function content(key) {
  const page = pages[key];
  let detail = '';
  if (key === 'featured') detail = entries(projects.filter(p=>p.featured && p.explore), p=>p.id==='africa'?'africa-cinema.html':(playables.find(x=>x.id===({fire:'thru_the_fire',streams:'streams',away:'i_was_away'}[p.id]))?.path || 'music-catalog.html'));
  if (key === 'playables') detail = entries(playables, p=>p.path);
  if (key === 'music') detail = projects.filter(p=>p.audio || p.tracks?.length).map(p=>`<article><h2>${esc(p.title)}</h2><p>${esc(p.description)}</p>${p.audio?`<a href="${esc(/^https?:/.test(p.audio)?p.audio:'../'+p.audio)}">Listen to ${esc(p.title)}</a>`:''}${p.tracks?.length?`<ul>${p.tracks.map(t=>`<li>${esc(t.title)}</li>`).join('')}</ul>`:''}</article>`).join('\n');
  if (key === 'videos') detail = entries(projects.filter(p=>p.video), p=>p.video)+'<p><a href="africa-cinema.html">Watch I Woke Up in Africa</a> · <a href="drive-in.html">Visit the 2FLY Drive-In Cinema</a></p>';
  if (key === 'africa') { const p=projects.find(p=>p.id==='africa'); detail=`<p>${esc(p?.story || p?.description)}</p><a href="africa-cinema.html">Watch the documentary</a><ul>${(p?.clips||[]).map(c=>`<li>${esc(c.title)}</li>`).join('')}</ul>`; }
  if (key === 'flyzone') detail='<h2>Create in the room with 2Fly</h2><p>Describe the feeling, choose the ingredients, or combine both. Choose a genre, mood, drums, tempo and instruments to shape your idea.</p><a href="../games/Flyzone/index.html">Open Flyzone Studio</a>';
  if (key === 'support') detail='<p>Your support helps create independent music, films, software and interactive stories.</p><a href="https://buy.stripe.com/cNi3cx2NGaN53rk1HG0Fi00">Help 2Fly create</a>';
  return `<section class="seo-introduction"><h1>${esc(page.heading)}</h1><p>${esc(page.description)}</p>${detail}<nav aria-label="Explore 2Fly">${Object.values(pages).map(p=>`<a href="${p.file}"${p===page?' aria-current="page"':''}>${esc(p.heading)}</a>`).join(' · ')} · <a href="drive-in.html">Drive In Cinema</a> · <a href="../ride/index.html">Ride and Vibe</a></nav></section>`;
}
let template = read('pages/site-overhaul.html').replace(/\r\n/g,'\n');
template = template.replace(/<!-- SEO:start -->[\s\S]*?<!-- SEO:end -->\n?/, '').replace(/<title>[\s\S]*?<\/title>\n?/, '').replace(/<meta name="description"[^>]*>\n?/, '');
template = template.replace(/<main id="appView" tabindex="-1">[\s\S]*?<\/main>/, '<main id="appView" tabindex="-1">__CONTENT__</main>');
template = template.replace(/<script>if\(!location.hash[^<]*<\/script>\n?/, '');
if (!template.includes('site-navigation.js')) template = template.replace('<meta name="theme-color"', '<script src="../js/site-seo-pages.js?v=seo-1"></script>\n  <script src="../js/site-navigation.js?v=seo-1" defer></script>\n  <meta name="theme-color"');
// Metadata must exist before the navigation script runs; defer also preserves parser ordering.
template = template.replace(/href="#(home|featured|playables|music|videos|flyzone|support|africa)"/g, (_,key)=>`href="${pages[key].file}"`);
for (const [key,page] of Object.entries(pages)) {
  write('pages/'+page.file, template.replace('</head>', metadata(page)+'\n</head>').replace('__CONTENT__',content(key)));
}
const extras = [
  {file:'pages/africa-cinema.html',title:'I Woke Up in Africa — Documentary by Keith Logan',description:'Watch I Woke Up in Africa, Keith Logan’s documentary journey through Rwanda, told in chapters of people, place and reflection.'},
  {file:'pages/drive-in.html',title:'2FLY Drive-In Cinema | I Was Away',description:'Park for a while at the 2FLY Drive-In Cinema and watch I Was Away, a film and music experience by 2Fly Keith Logan.'},
  {file:'ride/index.html',title:'Ride and Vibe | 2FLY Radio — Keith Logan',description:'Take the passenger seat, choose your ride and listen to 2FLY Radio in an immersive music experience by Keith Logan.'}
];
for (const page of extras) {
  page.url=base+page.file;
  page.schema={'@context':'https://schema.org','@type':'WebPage',url:page.url,name:page.title,description:page.description};
  let html=read(page.file).replace(/<!-- SEO:start -->[\s\S]*?<!-- SEO:end -->\n?/, '').replace(/<title>[\s\S]*?<\/title>/, '').replace(/<meta name="description"[^>]*>/, '');
  write(page.file,html.replace('</head>', metadata(page)+'\n</head>'));
}
const urls=[...Object.values(pages).map(p=>p.url),...extras.map(p=>p.url)];
write('sitemap.xml', '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+urls.map(url=>`  <url><loc>${esc(url)}</loc></url>`).join('\n')+'\n</urlset>\n');
write('robots.txt', '# For a GitHub project site, crawlers use https://2flykl.github.io/robots.txt.\n# This file is ready for a future deployment at the root of a custom domain.\nUser-agent: *\nAllow: /\n\nSitemap: '+base+'sitemap.xml\n');
console.log('Generated '+Object.keys(pages).length+' shell entry pages, '+extras.length+' standalone metadata blocks, and sitemap.xml.');
