(() => {
  'use strict';
  const config=window.CHOICE_CONFIG||{},stage=document.querySelector('#stage'),canvas=document.querySelector('#energy'),ctx=canvas.getContext('2d');
  const reduced=matchMedia('(prefers-reduced-motion: reduce)'),compact=matchMedia('(max-width:1100px), (max-height:500px)');
  const colors={blue:[71,149,255],red:[255,64,86]},state={active:null,selected:null,width:0,height:0,paths:{},raf:0};
  const buttons=[...document.querySelectorAll('[data-select]')];
  const particles=Array.from({length:120},(_,i)=>({color:i%2?'blue':'red',progress:Math.random(),speed:.04+Math.random()*.09,offset:(Math.random()-.5)*2,size:.6+Math.random()*1.6,phase:Math.random()*Math.PI*2}));
  function setActive(color){state.active=color;['blue','red'].forEach(c=>document.querySelectorAll('.'+c).forEach(el=>el.classList.toggle('active',color===c)))}
  document.querySelectorAll('[data-select],.choice').forEach(el=>{const color=el.dataset.select||el.dataset.choice;el.addEventListener('pointerenter',()=>setActive(color));el.addEventListener('pointerleave',()=>setActive(document.activeElement?.dataset.select||null));el.addEventListener('focusin',()=>setActive(color));el.addEventListener('focusout',()=>setActive(null))});
  document.querySelectorAll('.pill-art').forEach(el=>{const img=new Image();img.alt='';img.src=`assets/${el.closest('[data-select]').dataset.select}-pill.png`;img.decoding='async';el.appendChild(img)});
  function measure(){const rect=stage.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);state.width=rect.width;state.height=rect.height;canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);for(const color of ['blue','red']){const pill=document.querySelector(`.pill-target.${color}`).getBoundingClientRect(),panel=document.querySelector(`.choice.${color} .panel`).getBoundingClientRect();state.paths[color]={start:{x:pill.left+pill.width/2-rect.left,y:pill.top+pill.height/2-rect.top},end:{x:panel.left+panel.width*(color==='blue'?.67:.33)-rect.left,y:(compact.matches?panel.top:panel.bottom)-rect.top},bend:color==='blue'?-1:1}}if(reduced.matches)draw(performance.now(),0)}
  function point(path,t,offset=0,phase=0,time=0){return{x:path.start.x+(path.end.x-path.start.x)*t+Math.sin(t*Math.PI)*(path.bend*22+offset*27+Math.sin(t*7+phase+time)*7),y:path.start.y+(path.end.y-path.start.y)*t}}
  function draw(now,dt){ctx.clearRect(0,0,state.width,state.height);const time=now/1500;
    for(const color of ['blue','red']){const path=state.paths[color];if(!path)continue;const rgb=colors[color].join(','),active=state.active===color,glow=ctx.createRadialGradient(path.start.x,path.start.y,0,path.start.x,path.start.y,active?90:60);glow.addColorStop(0,`rgba(${rgb},${active?.25:.1})`);glow.addColorStop(1,`rgba(${rgb},0)`);ctx.fillStyle=glow;ctx.fillRect(path.start.x-100,path.start.y-100,200,200);
      for(let strand=0;strand<4;strand++){ctx.beginPath();for(let step=0;step<=40;step++){const p=point(path,step/40,(strand-1.5)*.5,strand*2,time);step?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y)}const gradient=ctx.createLinearGradient(path.start.x,path.start.y,path.end.x,path.end.y);gradient.addColorStop(0,`rgba(${rgb},${active?.5:.25})`);gradient.addColorStop(.7,`rgba(${rgb},${active?.3:.12})`);gradient.addColorStop(1,`rgba(${rgb},0)`);ctx.strokeStyle=gradient;ctx.lineWidth=active?1.4:.9;ctx.shadowBlur=active?18:10;ctx.shadowColor=`rgb(${rgb})`;ctx.stroke()}}
    for(const p of particles){const path=state.paths[p.color];if(!path)continue;const active=state.active===p.color;p.progress=(p.progress+dt*p.speed*(active?2.2:1))%1;const t=p.progress,pos=point(path,t,p.offset,p.phase,time);ctx.fillStyle=`rgba(${colors[p.color].join(',')},${Math.sin(t*Math.PI)*(active?.9:.5)})`;ctx.shadowColor=`rgb(${colors[p.color].join(',')})`;ctx.shadowBlur=active?13:7;ctx.beginPath();ctx.arc(pos.x,pos.y,p.size*(active?1.2:.8),0,Math.PI*2);ctx.fill()}ctx.shadowBlur=0;
  }
  let previous=performance.now();function tick(now){const dt=Math.min((now-previous)/1000,.05);previous=now;draw(now,dt);state.raf=requestAnimationFrame(tick)}
  function animate(){cancelAnimationFrame(state.raf);if(!reduced.matches&&!document.hidden&&!state.selected&&document.body.dataset.motion!=='paused'){previous=performance.now();state.raf=requestAnimationFrame(tick)}else draw(performance.now(),0)}
  addEventListener('choice-motion',animate);
  new ResizeObserver(measure).observe(stage);document.fonts.ready.then(measure);document.querySelector('.scene').addEventListener('load',measure);reduced.addEventListener('change',animate);document.addEventListener('visibilitychange',animate);measure();animate();
  function safeDestination(value){try{const url=new URL(value,location.href);return /^https?:$/.test(url.protocol)?url.href:null}catch{return null}}
  function exitDestination(){if(config.exitUrl)return safeDestination(config.exitUrl);const referrer=config.getReferrer?config.getReferrer():document.referrer;if(config.returnToReferrer&&referrer){try{const ref=new URL(referrer);if(ref.origin!==location.origin&&/^https?:$/.test(ref.protocol)&&!/(^|\.)(chatgpt\.com|openai\.com)$/.test(ref.hostname))return ref.href}catch{}}return null}
  function showExit(){document.querySelector('#experience').hidden=true;const destination=document.querySelector('#destination');destination.hidden=false;destination.classList.add('blue');document.querySelector('#destination-kicker').textContent='THE FAMILIAR';document.querySelector('#destination-title').textContent='Back to your world.';document.querySelector('#destination-copy').textContent='Nothing more to do. Close this tab and carry on where you left off.';document.querySelector('#transition').classList.remove('running');destination.focus()}
  function choose(color){if(state.selected)return;state.selected=color;setActive(color);buttons.forEach(b=>b.disabled=true);const overlay=document.querySelector('#transition'),pill=document.querySelector(`.pill-target.${color}`).getBoundingClientRect();overlay.className=`transition ${color} running`;overlay.style.setProperty('--origin-x',`${pill.left+pill.width/2}px`);overlay.style.setProperty('--origin-y',`${pill.top+pill.height/2}px`);setTimeout(()=>{const url=color==='red'?safeDestination(config.enterUrl||'features.html'):exitDestination();if(url){if(config.navigate)config.navigate(url);else location.assign(url)}else showExit();animate()},reduced.matches?0:1250)}
  buttons.forEach(button=>button.addEventListener('click',()=>choose(button.dataset.select)));
  document.querySelector('#return-choice').addEventListener('click',()=>{document.querySelector('#destination').hidden=true;document.querySelector('#experience').hidden=false;state.selected=null;buttons.forEach(b=>b.disabled=false);setActive(null);measure();animate();buttons[0].focus()});
  addEventListener('pageshow',event=>{if(event.persisted){state.selected=null;buttons.forEach(b=>b.disabled=false);document.querySelector('#transition').classList.remove('running');animate()}});
  if(config.introVideo){const video=document.createElement('video');video.className='intro-video';video.src=config.introVideo;video.poster=document.querySelector('.scene').src;video.muted=true;video.playsInline=true;video.autoplay=true;const skip=document.createElement('button');skip.className='skip-intro';skip.textContent='Skip intro';stage.classList.add('intro-playing');stage.append(video,skip);buttons.forEach(b=>b.disabled=true);function finish(){video.pause();video.remove();skip.remove();stage.classList.remove('intro-playing');buttons.forEach(b=>b.disabled=false)}video.addEventListener('ended',finish,{once:true});video.addEventListener('error',finish,{once:true});skip.addEventListener('click',finish);video.play().catch(finish)}
})();
