(()=>{
'use strict';
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d',{alpha:false});
const W=canvas.width,H=canvas.height,startBtn=document.getElementById('start'),overlay=document.getElementById('start-overlay'),fatal=document.getElementById('fatal');
const SONG='https://static.wixstatic.com/mp3/85e419_62dfb4b5acfc4747a02ad9eaeb643f29.mp3';
const A='assets/production/',B='assets/backgrounds/';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*clamp(t,0,1),rand=(a,b)=>a+Math.random()*(b-a),ease=t=>t*t*(3-2*t);
window.addEventListener('error',e=>{fatal.style.display='block';fatal.textContent='GAME ERROR: '+e.message;});
window.addEventListener('unhandledrejection',e=>{fatal.style.display='block';fatal.textContent='ASYNC ERROR: '+String(e.reason||'unknown');});

const sources={
 scene1:B+'scene1_sky.jpg',scene2:B+'scene2_runway.jpg',scene3:B+'scene3_maze.jpg',scene3city:B+'scene3_city.jpg',scene4:B+'scene4_storm.jpg',
 clouds:B+'cloud_layer.png',rain:B+'rain.png',speed:B+'speed_lines.png',
 planeIdle:A+'plane_idle.png',planeBank:A+'plane_bank.png',planeBurn:A+'plane_burn.png',planeExplode:A+'plane_explode.png',
 pianoIdle:A+'piano_idle.png',pianoDrive:A+'piano_drive.png',pianoBoost:A+'piano_boost.png',rampSmall:A+'ramp_small.png',rampRed:A+'ramp_red.png',
 boss:A+'algorithm_boss.png',explosion:A+'explosion.png',
 aerialDive:[0,1,2,3].map(i=>A+`aerial_dive_${i}.png`),aerialResist:[0,1,2,3].map(i=>A+`aerial_resist_${i}.png`),aerialSpin:[0,1,2,3].map(i=>A+`aerial_spin_${i}.png`),aerialAction:[0,1,2,3].map(i=>A+`aerial_action_${i}.png`),
 run:[0,1,2,3].map(i=>A+`v5_hero_run_${i}.png`),fire:[0,1,2,3].map(i=>A+`v5_hero_fire_${i}.png`),victory:[0,1,2].map(i=>A+`v5_hero_victory_${i}.png`),
 bots:[A+'bot_surveillance_orb.png',A+'bot_tracking_orb.png',A+'bot_interceptor.png',A+'bot_censorship_bot.png',A+'bot_firewall_sentinel.png',A+'bot_data_miner.png',A+'bot_corrupted_jammer.png',A+'bot_heavy_assault.png',A+'bot_manipulator.png',A+'bot_shield_projector.png']
};
const imgs={};
function loadImage(src){return new Promise((res,rej)=>{const im=new Image();im.onload=()=>res(im);im.onerror=()=>rej(new Error('Missing '+src));im.src=src;});}
async function loadAll(){let jobs=[];for(const [k,v] of Object.entries(sources)){if(typeof v==='string')jobs.push([k,v]);else v.forEach((s,i)=>jobs.push([`${k}_${i}`,s]));}const settled=await Promise.allSettled(jobs.map(async([k,s])=>[k,await loadImage(s)]));settled.forEach(r=>{if(r.status==='fulfilled')imgs[r.value[0]]=r.value[1]});return settled.filter(r=>r.status==='rejected').length;}

let songDur=128,totalDur=256,timing={};
function buildTiming(){const s=songDur/128;const parts=[['intro',17],['dive',43],['land',7],['runway',51],['grand',10],['maze',55],['stormJump',8],['boss',58],['ending',7]];let t=0;timing={};for(const [name,n] of parts){timing[name]={start:t,end:t+n*s,dur:n*s};t+=n*s;}totalDur=t;}
buildTiming();
let audio=null,audioStarted=false,audioStatus='READY',lastAudioSync=0;
function initAudio(){if(audio)return;audio=new Audio(SONG);audio.preload='metadata';audio.volume=.84;audio.loop=false;audio.playbackRate=1;audio.addEventListener('loadedmetadata',()=>{if(Number.isFinite(audio.duration)&&audio.duration>30){songDur=audio.duration;buildTiming();}});}
function tryAudio(){if(!started)return;initAudio();audioStarted=true;const desired=masterClock%songDur;try{if(Math.abs((audio.currentTime||0)-desired)>.8)audio.currentTime=desired;}catch(e){}audio.play().then(()=>audioStatus='PLAYING').catch(()=>audioStatus='CLICK / KEY TO RETRY');}
function syncAudio(){if(!audioStarted||!audio||masterClock>=totalDur)return;if(masterClock-lastAudioSync<1)return;lastAudioSync=masterClock;const desired=masterClock%songDur;try{if(audio.paused)audio.play().then(()=>audioStatus='PLAYING').catch(()=>audioStatus='CLICK / KEY TO RETRY');if(Math.abs(audio.currentTime-desired)>1.0)audio.currentTime=desired;audio.playbackRate=1;}catch(e){}}

const keys={},pressed={};let debug=false;
addEventListener('keydown',e=>{if(!keys[e.code])pressed[e.code]=true;keys[e.code]=true;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();if(e.code==='F2')debug=!debug;tryAudio();});
addEventListener('keyup',e=>keys[e.code]=false);canvas.addEventListener('pointerdown',tryAudio);
const down=c=>!!keys[c],tap=c=>{const v=!!pressed[c];pressed[c]=false;return v};

let started=false,last=0,masterClock=0,score=0,combo=0,hp=5,scene='intro';
let hero={x:W*.5,y:H*.55,frame:0,ft:0,jump:0,jv:0,spinT:0,lastDir:0,lastDirT:-9};
let plane={x:W*.5,y:H*.35},vehicle={x:W*.5,y:H*.76,airT:0,airMax:0},boss={x:W*.5,y:190,hp:140,max:140};
let enemies=[],shots=[],enemyShots=[],fx=[],roadObjects=[],spawnT=.6,fireT=0,specialT=0,escapeTaps=0,brace=0,grandCharge=0,stormCharge=0,finalCharge=0,floorPhase=0;
let scroll={a:0,b:0,c:0},cam={x:0,y:0,zoom:1,rot:0},camTarget={x:0,y:0,zoom:1,rot:0};

function reset(){masterClock=0;score=0;combo=0;hp=5;scene='intro';hero={x:W*.5,y:H*.55,frame:0,ft:0,jump:0,jv:0,spinT:0,lastDir:0,lastDirT:-9};plane={x:W*.5,y:H*.35};vehicle={x:W*.5,y:H*.76,airT:0,airMax:0};boss={x:W*.5,y:190,hp:140,max:140};enemies=[];shots=[];enemyShots=[];fx=[];roadObjects=[];spawnT=.5;fireT=0;specialT=0;escapeTaps=0;brace=0;grandCharge=0;stormCharge=0;finalCharge=0;floorPhase=0;scroll={a:0,b:0,c:0};cam={x:0,y:0,zoom:1,rot:0};if(audio){audio.pause();try{audio.currentTime=0}catch(e){}}audioStatus='STARTING…';}
function start(){reset();started=true;overlay.classList.add('hidden');initAudio();tryAudio();last=performance.now();requestAnimationFrame(loop);}

function segment(){for(const [name,v] of Object.entries(timing))if(masterClock>=v.start&&masterClock<v.end)return name;return 'complete';}
function local(name){const q=timing[name];return clamp((masterClock-q.start)/q.dur,0,1);}
function inputAxis(){return {x:(down('ArrowRight')||down('KeyD')?1:0)-(down('ArrowLeft')||down('KeyA')?1:0),y:(down('ArrowDown')||down('KeyS')?1:0)-(down('ArrowUp')||down('KeyW')?1:0)}};
function updateCamera(dt){const a=inputAxis();let leadX=a.x*28,leadY=a.y*12,z=1,r=0;if(scene==='dive'){leadX=a.x*36;leadY=a.y*22;if(a.y>0)z=.88;if(a.y<0)z=1.06;r=a.x*.025;}else if(scene==='runway'){leadX=a.x*34;leadY=(down('ArrowUp')||down('KeyW'))?-16:0;r=a.x*.01;}else if(scene==='maze'){leadX=a.x*42;leadY=a.y*18;z=vehicle.airT>0?.91:1;r=a.x*.012;}else if(scene==='boss'){leadX=a.x*30;leadY=-10;r=a.x*.008;}camTarget={x:leadX,y:leadY,zoom:z,rot:r};cam.x=lerp(cam.x,camTarget.x,dt*4);cam.y=lerp(cam.y,camTarget.y,dt*4);cam.zoom=lerp(cam.zoom,camTarget.zoom,dt*3.4);cam.rot=lerp(cam.rot,camTarget.rot,dt*3.2);}
function beginWorld(){ctx.save();ctx.translate(W/2,H/2);ctx.rotate(cam.rot);ctx.scale(cam.zoom,cam.zoom);ctx.translate(-W/2+cam.x,-H/2+cam.y);}
function endWorld(){ctx.restore();}
function cover(im,x=0,y=0,w=W,h=H){if(!im)return;const r=Math.max(w/im.width,h/im.height),sw=w/r,sh=h/r;ctx.drawImage(im,(im.width-sw)/2,(im.height-sh)/2,sw,sh,x,y,w,h);}
function scrolling(im,off,speedDir='y',alpha=1){if(!im)return;ctx.save();ctx.globalAlpha=alpha;if(speedDir==='y'){const o=((off%H)+H)%H;cover(im,0,o-H);cover(im,0,o);}else{const o=((off%W)+W)%W;cover(im,o-W,0);cover(im,o,0);}ctx.restore();}
function sprite(im,x,y,targetH,widthFactor=1,alpha=1,rot=0){if(!im)return{w:0,h:0};const h=targetH,w=im.width/im.height*h*widthFactor;ctx.save();ctx.globalAlpha=alpha;ctx.translate(x,y);ctx.rotate(rot);ctx.drawImage(im,-w/2,-h/2,w,h);ctx.restore();return{w,h};}
function arrImg(prefix,n){return imgs[`${prefix}_${Math.floor(hero.frame)%n}`]||imgs[`${prefix}_0`];}
function animate(dt,rate=.11){hero.ft+=dt;if(hero.ft>=rate){hero.ft=0;hero.frame++;}}

const botLabels=['SURVEILLANCE','TRACKING','INTERRUPTION','CENSORSHIP','FIREWALL','DATA MINER','JAMMER','AMPLIFICATION','MANIPULATION','SHIELD'];
function spawnEnemy(kind=scene){if(enemies.length>=6)return;let i=Math.floor(Math.random()*10);let y=kind==='dive'?H+120:rand(120,300);enemies.push({x:rand(120,1160),y,vx:rand(-35,35),vy:kind==='dive'?-rand(100,165):rand(20,50),img:i,hp:i===7?5:2,cool:rand(4,6),age:0,shoot:[2,3,7].includes(i)});}
function updateEnemies(dt){spawnT-=dt;if(spawnT<=0){spawnEnemy();spawnT=rand(.9,1.45);}const tgt=scene==='maze'?vehicle:hero;for(const e of enemies){e.age+=dt;e.cool-=dt;if(e.img===1)e.x+=(tgt.x-e.x)*dt*.15;else if(e.img===2)e.x+=Math.sin(e.age*3)*90*dt;else e.x+=e.vx*dt;e.y+=e.vy*dt;if(e.shoot&&e.cool<=0&&enemyShots.length<4){e.cool=rand(4.2,6.3);const dx=tgt.x-e.x,dy=tgt.y-e.y,l=Math.hypot(dx,dy)||1;enemyShots.push({x:e.x,y:e.y,vx:dx/l*170,vy:dy/l*170,life:4});}}enemies=enemies.filter(e=>e.hp>0&&e.x>-200&&e.x<W+200&&e.y>-200&&e.y<H+200);for(const s of enemyShots){s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;}enemyShots=enemyShots.filter(s=>s.life>0);}
function drawEnemies(){for(const e of enemies){sprite(imgs[`bots_${e.img}`],e.x,e.y,e.img===7?195:165,.98);ctx.fillStyle='#76e6ff';ctx.font='800 10px monospace';ctx.textAlign='center';ctx.fillText(botLabels[e.img],e.x,e.y-98);}}
function fire(){if(fireT>0||scene==='intro'||scene==='land'||scene==='grand'||scene==='stormJump'||scene==='ending')return;fireT=.22;const src=scene==='maze'?vehicle:hero;const dir=scene==='dive'?1:-1;const heavy=masterClock>timing.dive.start+timing.dive.dur*.72;for(const sp of (heavy?[-38,0,38]:[0]))shots.push({x:src.x,y:src.y+dir*35,vx:sp,vy:dir*650,life:1.8,pow:heavy?1.25:1});}
function updateCombat(dt){if(down('Space'))fire();fireT=Math.max(0,fireT-dt);specialT=Math.max(0,specialT-dt);for(const s of shots){s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;}for(const s of shots){for(const e of enemies){if(s.life<=0||e.hp<=0)continue;if(Math.hypot(s.x-e.x,s.y-e.y)<65){s.life=0;e.hp-=s.pow;score+=150;combo++;if(e.hp<=0)fx.push({x:e.x,y:e.y,t:.4});}}if(scene==='boss'&&s.life>0&&Math.hypot(s.x-boss.x,s.y-boss.y)<125){s.life=0;boss.hp-=s.pow;score+=100;}}shots=shots.filter(s=>s.life>0&&s.y>-120&&s.y<H+120);const tgt=scene==='maze'?vehicle:hero;for(const s of enemyShots){if(s.life>0&&Math.hypot(s.x-tgt.x,s.y-tgt.y)<38){s.life=0;hp=Math.max(1,hp-1);combo=0;}}if(down('ShiftLeft')&&specialT<=0){specialT=3.5;enemyShots=[];enemies.forEach(e=>e.hp-=1);fx.push({x:tgt.x,y:tgt.y,t:.55,sonic:true});}}
function drawCombat(){ctx.fillStyle='#6be8ff';for(const s of shots){ctx.beginPath();ctx.arc(s.x,s.y,6,0,Math.PI*2);ctx.fill();}ctx.fillStyle='#ff5147';for(const s of enemyShots){ctx.beginPath();ctx.arc(s.x,s.y,5,0,Math.PI*2);ctx.fill();}for(const f of fx){ctx.strokeStyle=`rgba(100,230,255,${clamp(f.t/.55,0,1)})`;ctx.lineWidth=f.sonic?6:3;ctx.beginPath();ctx.arc(f.x,f.y,(1-f.t/.55)*(f.sonic?170:70)+10,0,Math.PI*2);ctx.stroke();}}
function updateFx(dt){fx.forEach(f=>f.t-=dt);fx=fx.filter(f=>f.t>0);}

function prompt(text,sub=''){ctx.save();ctx.textAlign='center';ctx.fillStyle='rgba(0,0,0,.62)';ctx.fillRect(W/2-260,H-104,520,62);ctx.fillStyle='#fff';ctx.font='900 19px Arial';ctx.fillText(text,W/2,H-77);if(sub){ctx.fillStyle='#7ce5ff';ctx.font='700 12px Arial';ctx.fillText(sub,W/2,H-57);}ctx.restore();}
function bar(label,v){ctx.fillStyle='rgba(0,0,0,.65)';ctx.fillRect(W/2-180,H-132,360,13);ctx.fillStyle='#6be8ff';ctx.fillRect(W/2-180,H-132,360*clamp(v,0,1),13);ctx.fillStyle='#fff';ctx.font='700 11px Arial';ctx.textAlign='center';ctx.fillText(label,W/2,H-139);}

function drawIntro(dt){scene='intro';scroll.a+=20*dt;scrolling(imgs.scene1,scroll.a,'y');scrolling(imgs.clouds,scroll.a*1.6,'y',.12);const p=local('intro');let im=imgs.planeIdle;if(p>.35)im=imgs.planeBank;if(p>.62)im=imgs.planeBurn;if(p>.84)im=imgs.planeExplode;plane.x=W*.52+Math.sin(masterClock*1.2)*28;plane.y=H*.36+Math.sin(masterClock*2)*9;sprite(im,plane.x,plane.y,p>.84?235:195);updateEnemies(dt);drawEnemies();if(tap('KeyW')||tap('ArrowUp'))escapeTaps++;if(p>.55){prompt('TAP ↑ / W — GET OUT','Every press forces the escape forward.');bar('ESCAPE',escapeTaps/6);}if(p>.88){hero.frame+=dt*7;sprite(arrImg('aerial_dive',4),W*.54,H*.24+(p-.88)/.12*190,150,.95);}drawCombat();}
function updateDiveSpin(dt,xAxis){if(xAxis&&xAxis!==hero.lastDir){if(masterClock-hero.lastDirT<.34)hero.spinT=.62;hero.lastDir=xAxis;hero.lastDirT=masterClock;}hero.spinT=Math.max(0,hero.spinT-dt);}
function drawDive(dt){scene='dive';const a=inputAxis();updateDiveSpin(dt,a.x);const accel=a.y>0,resist=a.y<0;let speed=accel?350:resist?120:220;scroll.a-=speed*dt;scrolling(imgs.scene1,scroll.a,'y');scrolling(imgs.clouds,scroll.a*1.45,'y',.16);hero.x=clamp(hero.x+a.x*380*dt,110,1170);hero.y=clamp(hero.y+a.y*220*dt,120,585);animate(dt,.10);let im;if(hero.spinT>0){im=arrImg('aerialSpin',4);}else if(resist){im=arrImg('aerialResist',4);}else{im=arrImg('aerialDive',4);}sprite(im,hero.x,hero.y,resist?205:230,.98,1,a.x*.035);updateEnemies(dt);updateCombat(dt);drawEnemies();drawCombat();if(accel)prompt('POWER DIVE','DOWN = speed + wider camera');else if(resist)prompt('RESISTANCE','UP = upright precision / slower fall');}
function drawLand(dt){scene='land';scroll.a-=150*dt;scrolling(imgs.scene1,scroll.a,'y');const p=local('land');if(down('KeyW')||down('ArrowUp'))brace=Math.min(1,brace+dt*1.4);else brace=Math.max(0,brace-dt*.25);hero.frame+=dt*7;sprite(arrImg('aerialResist',4),W*.5,lerp(H*.28,H*.67,ease(p)),215,.98);for(let i=0;i<4;i++){ctx.strokeStyle=`rgba(100,230,255,${.65-i*.12})`;ctx.lineWidth=4;ctx.beginPath();ctx.ellipse(W/2,H*.82,70+i*55+(p*120),22+i*12,0,0,Math.PI*2);ctx.stroke();}prompt('HOLD ↑ / W — BRACE WITH THE 808','Bass pressure turns impact into a landing.');bar('LANDING BRACE',Math.max(brace,p*.75));}
function jumpUpdate(dt){if((tap('KeyW')||tap('ArrowUp'))&&hero.jump===0){hero.jv=-620;hero.jump=-1;}if(hero.jump!==0){hero.jv+=1500*dt;hero.jump+=hero.jv*dt;if(hero.jump>=0){hero.jump=0;hero.jv=0;}}}
function drawRunway(dt){scene='runway';const p=local('runway'),turn=p>.5;scroll.a+=(turn?-300:360)*dt;scrolling(imgs.scene2,scroll.a,'y');scrolling(imgs.rain,scroll.a*1.8,'y',.13);const a=inputAxis();hero.x=clamp(hero.x+a.x*370*dt,145,1135);jumpUpdate(dt);animate(dt,.09);const h=turn?lerp(130,225,(p-.5)*2):lerp(215,120,p*2),y=(turn?H*.79:lerp(H*.79,H*.47,p*2))+hero.jump;sprite(arrImg('run',4),hero.x,y,h,.82);if(turn){const q=(p-.5)*2;sprite(imgs.boss,W/2,165+q*90,95+q*q*455);}updateEnemies(dt);updateCombat(dt);drawEnemies();drawCombat();if(Math.abs(p-.5)<.035)prompt('TURN — FACE WHAT FOLLOWS YOU','The machine gets larger when you stop running from it.');}
function drawGrand(dt){scene='grand';scroll.a+=420*dt;scrolling(imgs.scene2,scroll.a,'y');const p=local('grand');if(down('KeyW')||down('ArrowUp'))grandCharge=Math.min(1,grandCharge+dt*1.3);else grandCharge=Math.max(0,grandCharge-dt*.15);ctx.fillStyle='rgba(255,80,55,.55)';for(let i=0;i<6;i++){const x=W*.20+i*145,y=H*.70-Math.sin(p*Math.PI*4+i)*18;ctx.beginPath();ctx.arc(x,y,20+p*30,0,Math.PI*2);ctx.fill();}sprite(imgs.pianoIdle,lerp(W+220,W*.58,ease(p)),H*.72,210);sprite(arrImg('run',4),W*.39,H*.72,180,.82);prompt('HOLD ↑ / W — CALL THE GRAND','Charge the keys. Then get aboard.');bar('THE GRAND',Math.max(grandCharge,p*.75));}
function spawnRamp(type='small'){roadObjects.push({type:'ramp',x:rand(W*.30,W*.70),y:-80,kind:type,hit:false});}
function updateRoadObjects(dt){for(const o of roadObjects)o.y+=330*dt;for(const o of roadObjects){if(o.hit||o.type!=='ramp')continue;if(Math.abs(o.y-vehicle.y)<55&&Math.abs(o.x-vehicle.x)<105){o.hit=true;vehicle.airT=o.kind==='large'?1.55:1.05;vehicle.airMax=vehicle.airT;score+=750;combo+=3;fx.push({x:vehicle.x,y:vehicle.y,t:.55,sonic:true});}}roadObjects=roadObjects.filter(o=>o.y<H+120);}
function drawRoadObjects(){for(const o of roadObjects){const im=o.kind==='large'?imgs.rampRed:imgs.rampSmall;if(im&&im.width>10)sprite(im,o.x,o.y,o.kind==='large'?95:72,1);else{ctx.fillStyle=o.kind==='large'?'#d34b39':'#3f9ed6';ctx.beginPath();ctx.moveTo(o.x-70,o.y+35);ctx.lineTo(o.x+70,o.y+35);ctx.lineTo(o.x+45,o.y-25);ctx.lineTo(o.x-45,o.y-25);ctx.closePath();ctx.fill();}}}
function drawMaze(dt){scene='maze';const p=local('maze');scroll.a+=430*dt;scroll.b+=90*dt;scrolling(imgs.scene3,scroll.a,'y');scrolling(imgs.scene3city,scroll.b,'x',.22);const a=inputAxis();vehicle.x=clamp(vehicle.x+a.x*430*dt,145,1135);vehicle.y=clamp(vehicle.y+a.y*235*dt,H*.47,H*.86);if(vehicle.airT>0)vehicle.airT=Math.max(0,vehicle.airT-dt);const air=vehicle.airT>0?Math.sin((1-vehicle.airT/vehicle.airMax)*Math.PI)*135:0;const rampTimes=[.13,.28,.43,.59,.73,.87];for(let i=0;i<rampTimes.length;i++){if(p>=rampTimes[i]&&!roadObjects.some(o=>o.marker===i)&&!roadObjects.some(o=>o.spawnMarker===i)){const o={type:'ramp',x:rand(W*.28,W*.72),y:-70,kind:i%3===2?'large':'small',hit:false,marker:i,spawnMarker:i};roadObjects.push(o);}}
updateRoadObjects(dt);updateEnemies(dt);updateCombat(dt);drawRoadObjects();drawEnemies();sprite(vehicle.airT>0?imgs.pianoBoost:imgs.pianoDrive,vehicle.x,vehicle.y-air,185,1);drawCombat();if(vehicle.airT>0){ctx.fillStyle='#75e6ff';ctx.font='900 18px Arial';ctx.textAlign='center';ctx.fillText('AIRTIME  ×2',vehicle.x,vehicle.y-air-120);}if(p<.08)prompt('THE ALGORITHM MAZE','Use ramps. Take air. Shoot the system from above.');}
function drawStormJump(dt){scene='stormJump';const p=local('stormJump');scroll.a+=500*dt;scrolling(imgs.scene3,scroll.a,'y');if(down('KeyW')||down('ArrowUp'))stormCharge=Math.min(1,stormCharge+dt*1.5);else stormCharge=Math.max(0,stormCharge-dt*.1);const y=lerp(H*.74,H*.26,ease(p)),x=lerp(W*.50,W*.58,p);ctx.fillStyle='#22384b';ctx.beginPath();ctx.moveTo(W*.28,H*.82);ctx.lineTo(W*.72,H*.82);ctx.lineTo(W*.62,H*.46);ctx.lineTo(W*.38,H*.46);ctx.closePath();ctx.fill();sprite(imgs.pianoBoost,x,y,lerp(190,155,p),1,1,p*.25);prompt("DON'T STOP — HOLD ↑ / W",'The road ends. The momentum does not.');bar('LAUNCH',Math.max(stormCharge,p*.8));if(p>.70){ctx.fillStyle=`rgba(120,220,255,${(p-.7)/.3})`;ctx.fillRect(0,0,W,H);}}
function drawBoss(dt){scene='boss';const p=local('boss');scroll.a+=(floorPhase?260:80)*dt;scrolling(imgs.scene4,scroll.a,'y');scrolling(imgs.rain,scroll.a*1.4,'y',.11);const a=inputAxis();hero.x=clamp(hero.x+a.x*360*dt,140,1140);jumpUpdate(dt);animate(dt,.10);sprite(arrImg('fire',4),hero.x,H*.79+hero.jump,205,.82);boss.x=W*.5+Math.sin(masterClock*.65)*220;boss.y=185+Math.sin(masterClock*1.1)*24;sprite(imgs.boss,boss.x,boss.y,335+Math.sin(masterClock*.4)*45);if(1-boss.hp/boss.max>.33)floorPhase=1;updateEnemies(dt);updateCombat(dt);drawEnemies();drawCombat();if(floorPhase&&p<.58)prompt('GROUND FAILURE','The arena is falling with you.');}
function drawEnding(dt){scene='ending';scroll.a+=130*dt;scrolling(imgs.scene4,scroll.a,'y');const p=local('ending');if(down('Space'))finalCharge=Math.min(1,finalCharge+dt*1.2);else finalCharge=Math.max(0,finalCharge-dt*.08);sprite(arrImg('fire',4),W*.5,H*.72,220,.82);sprite(imgs.boss,W*.5,H*.27,320*(1-p*.25),1,1-p*.6);for(let i=0;i<8;i++){ctx.strokeStyle=`rgba(${i%2?255:100},${i%2?90:220},255,${.2+i*.05})`;ctx.lineWidth=2;ctx.beginPath();ctx.arc(W*.5,H*.44,40+i*18+finalCharge*90,0,Math.PI*2);ctx.stroke();}prompt(p<.72?'HOLD FIRE — LOAD EVERY W.M.P.':'RELEASE','One signal. Every weapon. One choice.');bar('FINAL SIGNAL',Math.max(finalCharge,p*.8));}
function drawComplete(){scrolling(imgs.scene4,scroll.a,'y');ctx.fillStyle='rgba(0,0,0,.60)';ctx.fillRect(0,0,W,H);sprite(arrImg('victory',3),W*.5,H*.58,230,.82);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='900 55px Arial';ctx.fillText('THE SIGNAL SURVIVES.',W/2,H*.28);ctx.fillStyle='#79e5ff';ctx.font='700 19px Arial';ctx.fillText('AN ALGORITHM CAN PREDICT A CHOICE. IT CANNOT OWN ONE.',W/2,H*.35);}

function drawHUD(){ctx.save();ctx.setTransform(1,0,0,1,0,0);ctx.fillStyle='rgba(2,7,12,.84)';ctx.fillRect(25,18,475,108);ctx.fillStyle='#fff';ctx.font='900 25px Arial';ctx.textAlign='left';ctx.fillText('RETURN OF THE AVIATOR',38,48);ctx.fillStyle='#65ddff';ctx.font='700 15px Arial';ctx.fillText(masterClock>timing.dive.start+timing.dive.dur*.72?'808 BOOMER // BASS PRESSURE':'TONEARM // WHOLE NOTE',38,79);ctx.fillStyle=audioStatus==='PLAYING'?'#86efc5':'#ffb06b';ctx.font='700 13px Arial';ctx.fillText('♫ TOO FAST • '+audioStatus,270,79);ctx.fillStyle='#a6b6c5';ctx.font='700 13px Arial';ctx.fillText(`SCORE ${String(Math.floor(score)).padStart(7,'0')}   COMBO x${combo}`,38,106);for(let i=0;i<5;i++){ctx.fillStyle=i<hp?'#ff5148':'#26333f';ctx.fillRect(397+i*17,91,12,8);}if(scene==='boss'||scene==='ending'){ctx.fillStyle='rgba(0,0,0,.7)';ctx.fillRect(350,18,580,14);ctx.fillStyle='#ff4d44';ctx.fillRect(350,18,580*clamp(boss.hp/boss.max,0,1),14);}if(debug){ctx.fillStyle='rgba(0,0,0,.75)';ctx.fillRect(1015,18,245,122);ctx.fillStyle='#8be7ff';ctx.font='12px monospace';ctx.fillText(`SEGMENT ${scene}`,1030,42);ctx.fillText(`MASTER ${masterClock.toFixed(1)} / ${totalDur.toFixed(1)}`,1030,61);ctx.fillText(`SONG POS ${(masterClock%songDur).toFixed(1)} / ${songDur.toFixed(1)}`,1030,80);ctx.fillText(`BOTS ${enemies.length}  SHOTS ${enemyShots.length}`,1030,99);ctx.fillText(`CAM z${cam.zoom.toFixed(2)} x${cam.x.toFixed(0)}`,1030,118);}ctx.restore();}

function loop(now){if(!started)return;const dt=Math.min(.033,(now-last)/1000||0);last=now;masterClock=Math.min(totalDur+2,masterClock+dt);scene=segment();syncAudio();updateCamera(dt);ctx.fillStyle='#02050a';ctx.fillRect(0,0,W,H);beginWorld();if(scene==='intro')drawIntro(dt);else if(scene==='dive')drawDive(dt);else if(scene==='land')drawLand(dt);else if(scene==='runway')drawRunway(dt);else if(scene==='grand')drawGrand(dt);else if(scene==='maze')drawMaze(dt);else if(scene==='stormJump')drawStormJump(dt);else if(scene==='boss')drawBoss(dt);else if(scene==='ending')drawEnding(dt);else drawComplete();endWorld();updateFx(dt);drawHUD();requestAnimationFrame(loop);}

loadAll().then(missing=>{startBtn.disabled=false;startBtn.textContent=missing?`START EXPERIENCE (${missing} OPTIONAL ASSETS MISSING)`:'START EXPERIENCE';}).catch(err=>{fatal.style.display='block';fatal.textContent='LOAD ERROR: '+err.message;startBtn.disabled=false;startBtn.textContent='START EXPERIENCE';});
startBtn.addEventListener('click',start);
})();
